bird:
  log_syslog_all: true
  device_scan_time: 10
  device_semicolon: true
modules:
  iana:
    enabled: true
  dn42:
    enabled: false
  intra:
    enabled: true
intra:
  static:
    v4_routes:
    - prefix: 172.20.234.232/32
    v6_routes:
    - prefix: fd18:3e15:61d0::8/128
    - prefix: 2a14:7583:f224::d576/128
