template bgp ibgpeers {
#   vrf DN42_VRF;
    router   id DN42_OWNIP;
    local    as DN42_OWNAS;
    neighbor as DN42_OWNAS;
    multihop;

    ipv4 {
        table dn42_table_v4;
        import filter{
            if source = RTS_BGP && is_valid_dn42_network() && !is_self_dn42_net() || is_self_dn42_net() then{
                bgp_local_pref = 100;
                accept;
            } 
            else reject;
        };
        export filter {
            if net = DN42_OWNIP then accept;
            if source = RTS_BGP && is_valid_dn42_network() && !is_self_dn42_net() || is_self_dn42_net() then {
                accept;
            } 
            else reject;
        };
        next hop self;
        gateway recursive;
        extended next hop;
    };
    ipv6 {
        table dn42_table_v6;
        import filter{
            if source = RTS_BGP && is_valid_dn42_network_v6() && !is_self_dn42_net_v6() || is_self_dn42_net_v6() then{
                bgp_local_pref = 100;
                accept;
            } 
            else reject;
        };
        export filter {
            if net = DN42_OWNIPv6 then accept;
            if source = RTS_BGP && is_valid_dn42_network_v6() && !is_self_dn42_net_v6() || is_self_dn42_net_v6() then {
                accept;
            } 
            else reject;
        };
        next hop self;
        gateway recursive;
    };
};

include "ibgp/*";
