dn42:
  own_ip: 172.20.234.227
  own_ipv6: fd18:3e15:61d0::3
  region: 52
  country: 1392
  flapalerted:
    local: 172.20.234.227
    neighbor:
      address: 172.20.234.232
      port: 1790
    rpki_remote:
      address: 172.20.234.232
      port: 8083
  peers:
  - description: '@fx_net01'
    asn: 4242420014
    wireguard:
      public_key: RwS9qiSqkptO9QTje9stsxRD1CA/CR5HaDdNdPBydyU=
      listen_port: 20014
      fwmark: '4242'
      endpoint: jp.dn42.fxnet.top:22024
    lla: fe80::14:1
    bgp:
      extended_next_hop: true
  - description: '@guanranwang https://blog.ny4.dev/'
    asn: 4242420021
    wireguard:
      public_key: KW+H2qK9aDiqoLwvmtLjJ6Sbndbcn4vnJpjT/xz89BE=
      listen_port: 20021
      fwmark: '4242'
      endpoint: 178.239.125.6:22024
    ula: fd00:5d5b:797c::1
    src: fd18:3e15:61d0::3
  - description: https://dn42.routedbits.io/
    asn: 4242420207
    wireguard:
      public_key: Urnj0In2/ba5zBJ0+TvGN6/A3JFXZwWfJ3EVkc5A4Cs=
      listen_port: 20207
      fwmark: '4242'
      endpoint: 172.104.99.40:52024
    lla: fe80::207
    bgp:
      extended_next_hop: true
  - description: '@zxxwdd'
    asn: 4242420337
    wireguard:
      public_key: xZBEeAO1btrRvU7cpXTBqaw8CZsmxrfB0005OgljtmU=
      listen_port: 20337
      fwmark: '4242'
      endpoint: 8.211.131.51:22024
    lla: fe80::337
    bgp:
      extended_next_hop: true
  - description: '@opkgbot'
    asn: 4242420398
    wireguard:
      public_key: QQecM/0eCbRu5TNdyRxGpJTCo6aGolMb0kZAqLH5Oho=
      listen_port: 20398
      fwmark: '4242'
      endpoint: nrt.dn42.boletus.icu:22024
    lla: fe80::398
    bgp:
      extended_next_hop: true
  - description: dn42admin@maiyun.me https://maiyun.me/contact-me.html
    asn: 4242420893
    wireguard:
      public_key: J5aq5AYRv/GHfr90mVEOPRCQeLInGS3mnSpckuyWt04=
      listen_port: 20893
      fwmark: '4242'
      endpoint: jp02.dn42.maiyun.me:24224
    lla: fe80::893
    bgp:
      extended_next_hop: true
  - description: '@moenetdn42bot'
    asn: 4242420998
    wireguard:
      public_key: OkZGn8FGwUNuC9pt3kYIFeDNIx/wsGGEWikfOsBDFl8=
      listen_port: 20998
      fwmark: '4242'
      endpoint: jp1.dn42.moenet.work:32024
    lla: fe80::998:101:1:1
    bgp:
      extended_next_hop: true
  - description: '@Iridoideae'
    asn: 4242421023
    wireguard:
      public_key: pv0bwaUm/ppI7Yaoi7w0qrXX5EW7Qo2njTSNG19AHgM=
      listen_port: 21023
      fwmark: '4242'
      endpoint: 48.218.0.204:22024
    lla: fe80::1023:2
    bgp:
      extended_next_hop: true
  - description: https://highdef.network/
    asn: 4242421080
    wireguard:
      public_key: iJXjwJGGrUTQy/P3OXmZ5lM4cjrDAd9K+vonZVUZjxY=
      listen_port: 21080
      fwmark: '4242'
      endpoint: 85.113.70.18:22024
    lla: fe80::124
    bgp:
      extended_next_hop: true
  - description: '@antenna000 https://blog.yuyuko.com/post/7'
    asn: 4242421117
    wireguard:
      public_key: vZXB25Od9elWU4RKWp42MWNJrNtxJFgdmBkyYH/8Sj8=
      listen_port: 21117
      fwmark: '4242'
      endpoint: jp01.dn42.yuyuko.com:22024
    lla: fe80::1117
    bgp:
      extended_next_hop: true
  - description: https://blog.yuzu.im/mpage/182#node-tyo
    asn: 4242421131
    wireguard:
      public_key: 7ZLEhruv0R7V9DUEv+BHLr5fszpp/B55aKFtVoIACno=
      listen_port: 21131
      fwmark: '4242'
      endpoint: ipv4.tokyo.japan.dn42.yuzu.im:22024
    lla: fe80::1131
    bgp:
      extended_next_hop: true
  - description: '@Xeri_Xeiu https://blog.xeiu.top/dn42-info'
    asn: 4242421336
    wireguard:
      public_key: eacDn4IjHBMavV9IeilwPmrVDoVyKBkNhgK6qUBskiM=
      listen_port: 21336
      fwmark: '4242'
      endpoint: jp1-v6.dn42.xeiu.top:22024
    lla: fe80::1336
    bgp:
      extended_next_hop: true
  - asn: 4242421588
    description: https://www.chrismoos.com/dn42-peering/
    wireguard:
      public_key: unTYSat5YjkY+BY31Q9xLSfFhTUBvn3CiDCSZxbINVM=
      listen_port: 21588
      fwmark: '4242'
      endpoint: 202.182.101.118:58839
      address:
      - fe80::100/64
    lla: 172.20.16.145
  - description: '@messageleaf https://exploro.one/dn42'
    asn: 4242421771
    wireguard:
      public_key: 8dPYwTXeDyqtkONkmfVSmNli6I/k8Vc8hEWgC+ZWchw=
      listen_port: 21771
      fwmark: '4242'
      endpoint: 47.79.94.122:32603
    lla: fe80::2e0c:b32e:dca9:86a0
    bgp:
      extended_next_hop: true
  - description: 22024 https://jp42.kskb.eu.org/autopeer/action_page.php
    asn: 4242421817
    wireguard:
      public_key: LDtwAj4hsCOmZEnAcb2uzOH5FP1q43ploOoG/8tDeC4=
      listen_port: 21817
      fwmark: '4242'
      endpoint: jp.kskb.eu.org:22024
    lla: fe80::1817
    bgp:
      extended_next_hop: true
  - description: '@Luochancy https://dn42.luocynet.com/'
    asn: 4242421857
    wireguard:
      public_key: 4mrkVld0RCE5Tkn0v0xkiyMiT+cDQSRfL6AoMb3rzQg=
      listen_port: 21857
      fwmark: '4242'
      endpoint: jp1.dn42.luocynet.com:22024
    lla: fe80::1857:239
    bgp:
      extended_next_hop: true
  - description: '@imlonghao'
    asn: 4242421888
    wireguard:
      public_key: HND/VBClYdfCqAKGFmapwqOxg/KluPcv2u30rjD8+gk=
      listen_port: 21888
      fwmark: '4242'
      endpoint: 193.32.149.99:22024
    lla: fe80::1888
    bgp:
      extended_next_hop: true
  - description: https://luotianyi.eu/dn42/
    asn: 4242421999
    wireguard:
      public_key: vzCKl611U0MVeaIcNyb8gJgWk1p6HY6oHr1oE846Py8=
      listen_port: 21999
      fwmark: '4242'
      endpoint: tyo1.dn42.luotianyi.sbs:22024
    lla: fe80::1999
    bgp:
      extended_next_hop: true
  - description: https://iedon.net
    asn: 4242422189
    wireguard:
      public_key: u2ImAJn9ewce9YHN6HaqrR3Sr4Xsy5UaaJOLJ7gkSzs=
      listen_port: 22189
      fwmark: '4242'
      private_key_ref: tyo01-jp/dn42_4242422189
      endpoint: 150.230.193.167:36201
    lla: fe80::2189:ee
    bgp:
      extended_next_hop: true
  - description: '@cybercrushman'
    asn: 4242422289
    wireguard:
      public_key: iKsbvtsdrNwM130XGWvf621+BRuuQUmz1H9hlLCPEn4=
      listen_port: 22289
      fwmark: '4242'
      endpoint: jp-tyo02.pmman.tech:22024
    lla: fe80::2289
    bgp:
      extended_next_hop: true
  - description: '@moohric https://www.mhr.hk/posts/dn42-peering/'
    asn: 4242422279
    wireguard:
      public_key: Bt0gmHMrBBCgV8/k7n8ykA31YStGc55xmyLgMyB04E0=
      listen_port: 22279
      fwmark: '4242'
      endpoint: jp-nrt1.bb.mhr.hk:22024
    lla: fe80::2279
    bgp:
      extended_next_hop: true
  - description: '@charliealexander73'
    asn: 4242422363
    wireguard:
      public_key: rOKibWt5scg4L/0P4cx8ev3ikpK281srU/GVi8cIZgE=
      listen_port: 22363
      fwmark: '4242'
      mtu: 1380
      endpoint: oraclearm-jp.ca73.org:23672
    lla: fe80::ca73:2363:2024
    bgp:
      extended_next_hop: true
  - description: 23746 https://jp42.whojk.com/autopeer/action_page.php
    asn: 4242422717
    wireguard:
      public_key: Fw+pNtP7sPbrUMI2YTFcf5Fr1vtuuJoAmSTDd/ak5TU=
      listen_port: 22717
      fwmark: '4242'
      endpoint: 140.238.36.33:23746
    lla: fe80::2717
    bgp:
      extended_next_hop: true
  - description: '@AndyYan123'
    asn: 4242422921
    wireguard:
      public_key: nLyNhDOzsFUQ5LK5lrpHBlkKYkUzpzOm/p2iThlX3Dg=
      listen_port: 22921
      fwmark: '4242'
      endpoint: 156.231.116.81:22024
    lla: fe80::2921
    bgp:
      extended_next_hop: true
  - description: http://dn42.lare.cc/
    asn: 4242423035
    wireguard:
      public_key: oTPdRylNhX2O80e6rLejT9Fwzo7KWKZ7a3PUF4G9oEM=
      listen_port: 23035
      fwmark: '4242'
      endpoint: 193.111.30.186:22024
    lla: fe80::3035:134
    bgp:
      extended_next_hop: true
  - description: https://peer.dn42.6700.cc
    asn: 4242423088
    wireguard:
      public_key: b3gUz8an2+wSCvXAwuxGR7AnxKDUqqQMd1+LASo93R0=
      listen_port: 23088
      fwmark: '4242'
      private_key_ref: tyo01-jp/dn42_4242423088
      endpoint: 45.76.219.186:22024
    lla: fe80::3088:190
    bgp:
      extended_next_hop: true
  - description: '@Grayowo'
    asn: 4242423101
    wireguard:
      public_key: 3jkhBO/nKqWH1M377OhTZbwAXnnquy+Ggj4UbGtP+R8=
      listen_port: 23101
      fwmark: '4242'
      endpoint: 156.246.90.162:22024
    lla: fe80::3101:3
    bgp:
      extended_next_hop: true
  - description: '@Depressed_LeslieAlexander'
    asn: 4242423264
    wireguard:
      public_key: 3BbR49ma6Vk2xtYJ16TUhy0R/9V05N70BfHuZgUVfGE=
      listen_port: 23264
      fwmark: '4242'
      endpoint: 140.238.228.228:51822
    lla: fd64:8964:8964::2
    bgp:
      extended_next_hop: true
  - description: https://suki.ink/dn42
    asn: 4242423332
    wireguard:
      public_key: O75R09ATSL6ND0430jDIaBVKfGeAWoS0c6yXxeJyLUs=
      listen_port: 23332
      fwmark: '4242'
      endpoint: jp.dn42.h23.moe:22024
    lla: fe80::2333
    bgp:
      extended_next_hop: true
  - description: http://dn42.baka.pub/
    asn: 4242423374
    wireguard:
      public_key: N7iQzqWLPb6lpRlf7grQG6rEzQOvDZWkmsRDkRnniH0=
      listen_port: 23374
      fwmark: '4242'
      endpoint: jp01.dn42.baka.pub:22024
    lla: fe80::2999:226
    bgp:
      extended_next_hop: true
  - description: https://launchpadx.top/dn42 @jackzeng6666
    asn: 4242423702
    wireguard:
      public_key: G5v93xQO15JtNMKJehB2HFMB/ACX0ec6u6EUFbKblBY=
      listen_port: 23702
      fwmark: '4242'
      endpoint: iij.s.launchpadx.top:52024
    lla: fe80::3702
    bgp:
      extended_next_hop: true
  - description: https://blog.sherpherd.net/dn42.html
    asn: 4242423947
    wireguard:
      public_key: qwrsDI3bkHDOXUldYGJPSM3hTI7KqDpYbNMzKzB1Uko=
      listen_port: 23947
      fwmark: '4242'
      endpoint: 205.198.78.80:22024
    lla: fe80::3947:9
    bgp:
      extended_next_hop: true
  - description: '@Sm1rkBot https://blog.bitrate.top/dn42'
    asn: 4242423997
    wireguard:
      public_key: wsjN0FgfZBFzSZQ66biOkYRtyQWWMFvX3ICOwj70D0U=
      listen_port: 23997
      fwmark: '4242'
      endpoint: jp1.dn42.bitrate.studio:22024
    lla: fe80::3997
    bgp:
      extended_next_hop: true
  - description: '@charliemoomoo'
    asn: 4242423999
    wireguard:
      public_key: mMGGxtEqsagrx1Raw57C2H3Stl6ch/cUuF7y08eVgBE=
      listen_port: 23999
      fwmark: '4242'
      endpoint: tyo.node.cowgl.tech:32024
    lla: fe80::3999
    bgp:
      extended_next_hop: true
  ix:
    sessions: []
