wireguard:
  default_private_key_ref: tyo01-jp/default
  interfaces:
  - name: dn42_4242421040
    address:
    - fe80::2024/64
    listen_port: 21040
    table: 'off'
    peer:
      public_key: SwLhWz2c14bgSYBouIRUvs7m4NGWWmRLD4xW1bLWkHg=
      allowed_ips:
      - 10.0.0.0/8
      - 172.20.0.0/14
      - 172.31.0.0/16
      - fd00::/8
      - fe00::/8
      endpoint: shama-tokyo-jp02.dn42-endpoints.chihuo2104.dev:22024
    post_up:
    - sysctl -w net.ipv6.conf.%i.autoconf=0
    fwmark: '4242'
  - name: dn42_4242421411
    address:
    - fe80::2024/64
    listen_port: 21411
    table: 'off'
    peer:
      public_key: N7iQzqWLPb6lpRlf7grQG6rEzQOvDZWkmsRDkRnniH0=
      allowed_ips:
      - 10.0.0.0/8
      - 172.20.0.0/14
      - 172.31.0.0/16
      - fd00::/8
      - fe00::/8
      endpoint: jp01.dn42.baka.pub:22024
    post_up:
    - sysctl -w net.ipv6.conf.%i.autoconf=0
    fwmark: '4242'
