bird:
  log_syslog_all: true
  device_scan_time: 10
  device_semicolon: true
modules:
  iana:
    enabled: true
    includes:
    - rpki.conf
    - filter.conf
    - static.conf
    - upstream.conf
    - peer.conf
    - downstream.conf
    - ibgp.conf
  dn42:
    enabled: false
    includes: []
  intra:
    enabled: true
    includes:
    - filter.conf
    - ibgp.conf
    - static.conf
intra:
  static:
    v4_routes:
    - prefix: 172.20.234.231/32
    v6_routes:
    - prefix: fd18:3e15:61d0::7/128
    - prefix: 2a14:7583:f224::872c/128
