protocol bgp inet_feed_bgptools {
    local as INET_OWNAS;
    neighbor 185.230.223.74 as 212232;
    multihop;
    router id INET_ROUTER_ID;

    ipv6 {
        add paths yes;
        import none;
        export all;
    };
}
