template bgp inet_upstream {
    local as INET_OWNAS;
    path metric 1;
    multihop;
    router id INET_ROUTER_ID;
    
    ipv6 {
        import filter {
            if net ~ [::/0] then reject;
            krt_prefsrc=INET_OWNIPv6;
            accept;
        };
        export filter {
            if is_self_inet_v6() then accept;
            reject;
        };
    };

    graceful restart; 
}

protocol bgp 'inet_upstream_53808' from inet_upstream{
    description "MoeDove - Lycheen";
    local fc00:300::f:1;
    neighbor fc00:300::1 as 53808;
}

protocol bgp 'inet_upstream_205729' from inet_upstream{
    description "LoliNya";
    local fc00:300::f:1;
    neighbor fc00:300::d:1 as 207529;
}
