wireguard:
  default_private_key_ref: lax-us/default
  interfaces:
  - name: dn42_4242420150
    address:
    - fe80::2024/64
    listen_port: 20150
    table: 'off'
    peer:
      public_key: 1o0XfQvBM1gqknqzfuOnVmf2RjRTHuyMZYNipSSb2TQ=
      allowed_ips:
      - 10.0.0.0/8
      - 172.20.0.0/14
      - 172.31.0.0/16
      - fd00::/8
      - fe00::/8
      endpoint: iad.darkpoint.xyz:22024
    post_up:
    - sysctl -w net.ipv6.conf.%i.autoconf=0
  - name: dn42_4242420167
    address:
    - fe80::2024/64
    listen_port: 20167
    table: 'off'
    peer:
      public_key: IRpAYNTZg1YKumLqOstDOLh6iJKAwQEKC5YDFPb2Bm4=
      allowed_ips:
      - 10.0.0.0/8
      - 172.20.0.0/14
      - 172.31.0.0/16
      - fd00::/8
      - fe00::/8
      endpoint: sfo1.dn42.42420167.xyz:22024
    post_up:
    - sysctl -w net.ipv6.conf.%i.autoconf=0
  - name: dn42_4242420207
    address:
    - fe80::2024/64
    listen_port: 20207
    table: 'off'
    peer:
      public_key: s4uGYMeLV30vO/Z3+c1qrg/YA1eIMRVFYUsZEGD1hH8=
      allowed_ips:
      - 10.0.0.0/8
      - 172.20.0.0/14
      - 172.31.0.0/16
      - fd00::/8
      - fe00::/8
      endpoint: router.lax1.routedbits.com:52024
    post_up:
    - sysctl -w net.ipv6.conf.%i.autoconf=0
  - name: dn42_4242420253
    address:
    - fe80::2024/64
    listen_port: 20253
    table: 'off'
    peer:
      public_key: C3SneO68SmagisYQ3wi5tYI2R9g5xedKkB56Y7rtPUo=
      allowed_ips:
      - 10.0.0.0/8
      - 172.20.0.0/14
      - 172.31.0.0/16
      - fd00::/8
      - fe00::/8
      endpoint: lv.dn42.moe233.net:22024
    post_up:
    - sysctl -w net.ipv6.conf.%i.autoconf=0
  - name: dn42_4242420298
    address:
    - fe80::2024/64
    listen_port: 20298
    table: 'off'
    peer:
      public_key: qp/KHe+/6jf3/Cvbkw5/0gtJih+HzhpxW0UnLXMEHiw=
      allowed_ips:
      - 10.0.0.0/8
      - 172.20.0.0/14
      - 172.31.0.0/16
      - fd00::/8
      - fe00::/8
      endpoint: node3.ox5.cc:22024
    post_up:
    - sysctl -w net.ipv6.conf.%i.autoconf=0
  - name: dn42_4242420337
    address:
    - fe80::2024/64
    listen_port: 20337
    table: 'off'
    peer:
      public_key: QK813SDMiaIhfBw9VOkpTCgQSLdUNFDmSphymv5c7To=
      allowed_ips:
      - 10.0.0.0/8
      - 172.20.0.0/14
      - 172.31.0.0/16
      - fd00::/8
      - fe00::/8
      endpoint: lax01.dn42.wwrr.ru:22024
    post_up:
    - sysctl -w net.ipv6.conf.%i.autoconf=0
    mtu: 1320
  - name: dn42_4242420358
    address:
    - fe80::2024/64
    listen_port: 20358
    table: 'off'
    peer:
      public_key: 7HzHyeA2M7yo/zVmc+e0zG+I7j2SnIx+7ZpXOca93mg=
      allowed_ips:
      - 10.0.0.0/8
      - 172.20.0.0/14
      - 172.31.0.0/16
      - fd00::/8
      - fe00::/8
      endpoint: 45.32.129.207:22024
    post_up:
    - sysctl -w net.ipv6.conf.%i.autoconf=0
  - name: dn42_4242420398
    address:
    - fe80::2024/64
    listen_port: 20398
    table: 'off'
    peer:
      public_key: oAPy0U2qVuSR8PyPLmVLEgWLBKrOq4kcLNLAOVZL10M=
      allowed_ips:
      - 10.0.0.0/8
      - 172.20.0.0/14
      - 172.31.0.0/16
      - fd00::/8
      - fe00::/8
      endpoint: lax.dn42.boletus.icu:22024
    post_up:
    - sysctl -w net.ipv6.conf.%i.autoconf=0
  - name: dn42_4242420721
    address:
    - fe80::2024/64
    listen_port: 20721
    table: 'off'
    peer:
      public_key: HBn/8dyDkC8z4kY5tGZsG3d7iyyc8SWwl5c93po580w=
      allowed_ips:
      - 10.0.0.0/8
      - 172.20.0.0/14
      - 172.31.0.0/16
      - fd00::/8
      - fe00::/8
      endpoint: 24.199.110.90:22024
    post_up:
    - sysctl -w net.ipv6.conf.%i.autoconf=0
  - name: dn42_4242420893
    address:
    - fe80::2024/64
    listen_port: 20893
    table: 'off'
    peer:
      public_key: 6BFCe8vi6R9magcs/BqZbSqblNNqR/jcrNt1E7/NDD8=
      allowed_ips:
      - 10.0.0.0/8
      - 172.20.0.0/14
      - 172.31.0.0/16
      - fd00::/8
      - fe00::/8
      endpoint: uc01.dn42.maiyun.me:24224
    post_up:
    - sysctl -w net.ipv6.conf.%i.autoconf=0
  - name: dn42_4242421023
    address:
    - fe80::2024/64
    listen_port: 21023
    table: 'off'
    peer:
      public_key: yHtmGTi6r9AtrSeTZyl2yce6nHdSVcc017VMI1s9HH8=
      allowed_ips:
      - 10.0.0.0/8
      - 172.20.0.0/14
      - 172.31.0.0/16
      - fd00::/8
      - fe00::/8
      endpoint: lax-02.node.svc.moe:22024
    post_up:
    - sysctl -w net.ipv6.conf.%i.autoconf=0
  - name: dn42_4242421117
    address:
    - fe80::2024/64
    listen_port: 21117
    table: 'off'
    peer:
      public_key: PW/+rv0B8e4tUJ9j1TWscx1sl36WwhPh9adEqoM7Jic=
      allowed_ips:
      - 10.0.0.0/8
      - 172.20.0.0/14
      - 172.31.0.0/16
      - fd00::/8
      - fe00::/8
      endpoint: us01.dn42.yuyuko.com:22024
    post_up:
    - sysctl -w net.ipv6.conf.%i.autoconf=0
  - name: dn42_4242421123
    address:
    - fe80::2024/64
    listen_port: 21123
    table: 'off'
    peer:
      public_key: Z6OKJSR1sxMBgUd1uXEe/UxoBsOvRgbTnexy7z/ryUI=
      allowed_ips:
      - 10.0.0.0/8
      - 172.20.0.0/14
      - 172.31.0.0/16
      - fd00::/8
      - fe00::/8
    post_up:
    - sysctl -w net.ipv6.conf.%i.autoconf=0
  - name: dn42_4242421534
    address:
    - fe80::2024/64
    listen_port: 21534
    table: 'off'
    peer:
      public_key: G2pN3V0dtE/fGltPoOPwEkvZ7wC7TLmpr9gR3x/QUTk=
      allowed_ips:
      - 10.0.0.0/8
      - 172.20.0.0/14
      - 172.31.0.0/16
      - fd00::/8
      - fe00::/8
      endpoint: 152.53.208.136:22024
    post_up:
    - sysctl -w net.ipv6.conf.%i.autoconf=0
  - name: dn42_4242421771
    address:
    - fe80::2024/64
    listen_port: 21771
    table: 'off'
    peer:
      public_key: XC+KJ25WHrn6WxPYkiQOj1FPcaKgMRD4cCyxahqr1Ws=
      allowed_ips:
      - 10.0.0.0/8
      - 172.20.0.0/14
      - 172.31.0.0/16
      - fd00::/8
      - fe00::/8
      endpoint: 148.135.56.215:32629
    post_up:
    - sysctl -w net.ipv6.conf.%i.autoconf=0
  - name: dn42_4242421817
    address:
    - fe80::2024/64
    listen_port: 21817
    table: 'off'
    peer:
      public_key: dZzVdXbQPnWPpHk8QfW/p+MfGzAkMBuWpxEIXzQCggY=
      allowed_ips:
      - 10.0.0.0/8
      - 172.20.0.0/14
      - 172.31.0.0/16
      - fd00::/8
      - fe00::/8
      endpoint: us.kskb.eu.org:22024
    post_up:
    - sysctl -w net.ipv6.conf.%i.autoconf=0
  - name: dn42_4242421919
    address:
    - fe80::2024/64
    listen_port: 21919
    table: 'off'
    peer:
      public_key: yOt9PIXDa4pzAE+XMzDv7J+CYO2qf53fnF9MvLy4iQ8=
      allowed_ips:
      - 10.0.0.0/8
      - 172.20.0.0/14
      - 172.31.0.0/16
      - fd00::/8
      - fe00::/8
      endpoint: 149.28.212.242:42024
    post_up:
    - sysctl -w net.ipv6.conf.%i.autoconf=0
  - name: dn42_4242422189
    address:
    - fe80::2024/64
    listen_port: 22189
    table: 'off'
    peer:
      public_key: DIw4TKAQelurK10Sh1qE6IiDKTqL1yciI5ItwBgcHFA=
      allowed_ips:
      - 10.0.0.0/8
      - 172.20.0.0/14
      - 172.31.0.0/16
      - fd00::/8
      - fe00::/8
      endpoint: us-lax.dn42.iedon.net:57115
    post_up:
    - sysctl -w net.ipv6.conf.%i.autoconf=0
  - name: dn42_4242422279
    address:
    - fe80::2024/64
    listen_port: 22279
    table: 'off'
    peer:
      public_key: WCVsWHNq+VeafZ7agkfkafZIoC/8oHF46D07PkOVljA=
      allowed_ips:
      - 10.0.0.0/8
      - 172.20.0.0/14
      - 172.31.0.0/16
      - fd00::/8
      - fe00::/8
      endpoint: us-sjc1.bb.mhr.hk:22024
    post_up:
    - sysctl -w net.ipv6.conf.%i.autoconf=0
  - name: dn42_4242422466
    address:
    - fe80::2024/64
    listen_port: 22466
    table: 'off'
    peer:
      public_key: tA6SZZYpCdr4zkkk2pCpuDDiyxcHIsksOhwWnzLIVw8=
      allowed_ips:
      - 10.0.0.0/8
      - 172.20.0.0/14
      - 172.31.0.0/16
      - fd00::/8
      - fe00::/8
      endpoint: 23.95.205.128:22024
    post_up:
    - sysctl -w net.ipv6.conf.%i.autoconf=0
  - name: dn42_4242422467
    address:
    - fe80::2024/64
    listen_port: 22467
    table: 'off'
    peer:
      public_key: Nn73gI6XYCHxKWybWPwFgNQM8/s5R3UzN6VqutUC/3s=
      allowed_ips:
      - 10.0.0.0/8
      - 172.20.0.0/14
      - 172.31.0.0/16
      - fd00::/8
      - fe00::/8
      endpoint: 77.111.110.27:22024
    post_up:
    - sysctl -w net.ipv6.conf.%i.autoconf=0
  - name: dn42_4242422717
    address:
    - fe80::2024/64
    listen_port: 22717
    table: 'off'
    peer:
      public_key: L4+efr10ZM0J80nDeO5mHw25nq9LC5UBrYtP8T1I9n4=
      allowed_ips:
      - 10.0.0.0/8
      - 172.20.0.0/14
      - 172.31.0.0/16
      - fd00::/8
      - fe00::/8
      endpoint: usw.vm.whojk.com:23154
    post_up:
    - sysctl -w net.ipv6.conf.%i.autoconf=0
  - name: dn42_4242423088
    address:
    - fe80::2024/64
    listen_port: 23088
    table: 'off'
    peer:
      public_key: QSAeFPotqFpF6fFe3CMrMjrpS5AL54AxWY2w1+Ot2Bo=
      allowed_ips:
      - 10.0.0.0/8
      - 172.20.0.0/14
      - 172.31.0.0/16
      - fd00::/8
      - fe00::/8
      endpoint: lax1-us.dn42.6700.cc:22024
    post_up:
    - sysctl -w net.ipv6.conf.%i.autoconf=0
  - name: dn42_4242423128
    address:
    - fe80::2024/64
    listen_port: 23128
    table: 'off'
    peer:
      public_key: YwnQqLlObD7TrpGKz4qhHh5C6hatuxIU3zcdjXpYP00=
      allowed_ips:
      - 10.0.0.0/8
      - 172.20.0.0/14
      - 172.31.0.0/16
      - fd00::/8
      - fe00::/8
      endpoint: dn42.la.us.gtio.de:52024
    post_up:
    - sysctl -w net.ipv6.conf.%i.autoconf=0
  - name: dn42_4242423310
    address:
    - fe80::2024/64
    listen_port: 23310
    table: 'off'
    peer:
      public_key: qEffOA35Oe2IFUFXv7KTGGZ5SV3XmrM+IxTdzHEDmCg=
      allowed_ips:
      - 10.0.0.0/8
      - 172.20.0.0/14
      - 172.31.0.0/16
      - fd00::/8
      - fe00::/8
      endpoint: v4.lax01.edge.r1.tmpfs.dev:22024
    post_up:
    - sysctl -w net.ipv6.conf.%i.autoconf=0
  - name: dn42_4242423797
    address:
    - fe80::2024/64
    listen_port: 23797
    table: 'off'
    peer:
      public_key: 4RtBDlHlTLec0ThvkGKjwiyuDk0YspugIMHeUdaNZmE=
      allowed_ips:
      - 10.0.0.0/8
      - 172.20.0.0/14
      - 172.31.0.0/16
      - fd00::/8
      - fe00::/8
      endpoint: 155.94.164.158:50097
      preshared_key_ref: lax-us/dn42_4242423797
    post_up:
    - sysctl -w net.ipv6.conf.%i.autoconf=0
  - name: dn42_4242423914
    address:
    - fe80::2024/64
    listen_port: 23914
    table: 'off'
    peer:
      public_key: sLbzTRr2gfLFb24NPzDOpy8j09Y6zI+a7NkeVMdVSR8=
      allowed_ips:
      - 10.0.0.0/8
      - 172.20.0.0/14
      - 172.31.0.0/16
      - fd00::/8
      - fe00::/8
      endpoint: us3.g-load.eu:22024
    post_up:
    - sysctl -w net.ipv6.conf.%i.autoconf=0
  - name: dn42_4242423999
    address:
    - fe80::2024/64
    listen_port: 23999
    table: 'off'
    peer:
      public_key: jhOukGNAKHI8Ivn8uI1TS25n5ho/rVlKFfenGmwCVlg=
      allowed_ips:
      - 10.0.0.0/8
      - 172.20.0.0/14
      - 172.31.0.0/16
      - fd00::/8
      - fe00::/8
      endpoint: lax.node.cowgl.tech:22024
    post_up:
    - sysctl -w net.ipv6.conf.%i.autoconf=0
  - name: intra_fra01
    address:
    - fe80::2024:229/64
    listen_port: 10228
    table: 'off'
    peer:
      public_key: 4zEFOrqHdIDPcjvu6NwbE1AAYBH1bA+SAowysX5fRT4=
      allowed_ips:
      - 0.0.0.0/0
      - ::/0
      endpoint: ipv6.fra01-de.ecs.iyoroy-infra.top:10229
    post_up:
    - sysctl -w net.ipv6.conf.%i.autoconf=0
  - name: intra_hkg02
    address:
    - fe80::2024:229/64
    listen_port: 10225
    table: 'off'
    peer:
      public_key: bg+KnzVupBrOQntHFFVzvBx+3sqYVoyJRantT6m5fm8=
      allowed_ips:
      - 0.0.0.0/0
      - ::/0
      endpoint: ipv4.hkg02-cn.ecs.iyoroy-infra.top:10229
    post_up:
    - sysctl -w net.ipv6.conf.%i.autoconf=0
  - name: intra_tyo
    address:
    - fe80::2024:229/64
    listen_port: 10227
    table: 'off'
    peer:
      public_key: Sh62ZCxnEcXyLq49mLP1jF4C2vWKhKMxjtZHxVUAQg4=
      allowed_ips:
      - 0.0.0.0/0
      - ::/0
      endpoint: ipv4.tyo-jp.ecs.iyoroy-infra.top:10229
    post_up:
    - sysctl -w net.ipv6.conf.%i.autoconf=0
