define DN42_OWNAS                = 4242422024;
define DN42_OWNIP                = 100.64.0.1;
define DN42_OWNIPv6              = fd18:3e15:61d0::4;
define DN42_OWNNET               = 172.20.234.224/28;
define DN42_OWNNETv6             = fd18:3e15:61d0::/48;
define DN42_OWNNETSET            = [ 172.20.234.224/28+ ];
define DN42_OWNNETSETv6          = [ fd18:3e15:61d0::/48+ ];
define DN42_REGION               = 41;
define DN42_COUNTRY              = 1276;

define INTRA_CONFEDERATION_START = 4220240000;
define INTRA_CONFEDERATION_END   = 4220249999;
define INTRA_OWNAS               = 4220240101;
define INTRA_ROUTERID            = 100.64.0.1;
define INTRA_PREFIX_V4           = [ 100.64.0.0/16+ ];
define INTRA_PREFIX_V6           = [ fd18:3e15:61d0:cafe::/64+ ];

protocol device {
    scan time 10;
}

include "filter.conf";

include "dn42/filter.conf";
include "dn42/flapalerted.conf";
# include "dn42/rpki.conf"; # invalid 
include "dn42/ix.conf";

include "intra/filter.conf";
include "intra/ibgp.conf";
include "intra/static.conf";

include "kernel.conf";
