protocol bgp dn42_flapalerted {
    router id DN42_OWNIP;
    local 172.20.234.228 as 4242422024; # This address cannot be ::1, it must be another address assigned to the host
    neighbor 172.20.234.226 as 4242422024 port 1790;

    ipv4 {
        table dn42_table_v4;
        add paths on;
        export all;
        import none;
        extended next hop on;
    };

    ipv6 {
        table dn42_table_v6;
        add paths on;
        export all;
        import none;
    };
}

roa4 table dn42_roa_flap_v4;
roa6 table dn42_roa_flap_v6;

protocol rpki dn42_rpki_flapalerted {
    roa4 { table dn42_roa_flap_v4; };
    roa6 { table dn42_roa_flap_v6; };
    remote 172.20.234.226 port 8083;   
    max version 1;
    retry keep 10;
};
