protocol static intra_static_v4{
    route 100.64.0.1/32 reject{
        bgp_large_community.add((4242422024,1,1)); # control: allow to be advertised on both DN42 infrastructures
        bgp_large_community.add((4242422024,2,0)); # origin identify: private network
        bgp_large_community.add((4242422024,2,100)); # origin identify: from downstream
        bgp_large_community.add((4242422024,65535,65281)); # control: no-export
    };

    ipv4 {
        import all;
        export none;
    };
}

protocol static intra_static_v6{
    route fd18:3e15:61d0:cafe::1/128 reject{
        bgp_large_community.add((4242422024,1,1)); # control: allow to be advertised on both DN42 infrastructures
        bgp_large_community.add((4242422024,2,0)); # origin identify: private network
        bgp_large_community.add((4242422024,2,100)); # origin identify: from downstream
        bgp_large_community.add((4242422024,65535,65281)); # control: no-export
    };

    ipv6 {
        import all;
        export none;
    };
}
