bird:
  log_syslog_all: true
  device_scan_time: 10
  device_semicolon: true
modules:
  iana:
    enabled: true
    includes:
    - rpki.conf
    - filter.conf
    - static.conf
    - upstream.conf
    - peer.conf
    - downstream.conf
  dn42:
    enabled: true
    includes:
    - rpki.conf
    - flapalerted.conf
    - filter.conf
    - static.conf
    - ebgp.conf
  intra:
    enabled: true
    includes:
    - filter.conf
    - ibgp.conf
    - static.conf
intra:
  own_as: 4220240105
  router_id: DN42_OWNIP
  static:
    v4_routes:
    - prefix: 172.20.234.234/32
      communities:
      - [4242422024, 1, 1]
      - [4242422024, 2, 0]
      - [4242422024, 2, 100]
      - [4242422024, 65535, 65281]
      - [65535, 65281]
    v6_routes:
    - prefix: fd18:3e15:61d0::10/128
      communities:
      - [4242422024, 1, 1]
      - [4242422024, 2, 0]
      - [4242422024, 2, 100]
      - [4242422024, 65535, 65281]
      - [65535, 65281]
    - prefix: 2a14:7583:f228::6f78/128
      communities:
      - [4242422024, 1, 1]
      - [4242422024, 2, 0]
      - [4242422024, 2, 100]
      - [4242422024, 65535, 65281]
      - [65535, 65281]
  ibgp_sessions:
  - file: tyo01.conf
    protocol: intra_ibgp_tyo01
    neighbor:
      address: fe80::2024:227
      interface: intra_tyo01
    ipv4:
      import_policy: full
      export_policy: full
    ipv6:
      import_policy: full
      export_policy: full
  - file: tyo02.conf
    protocol: intra_ibgp_tyo02
    neighbor:
      address: fe80::2024:230
      interface: intra_tyo02
    ipv4:
      import_policy: full
      export_policy: full
    ipv6:
      import_policy: full
      export_policy: full
  - file: pvg01.conf
    protocol: intra_ibgp_pvg01
    neighbor:
      address: fe80::2024:233
      interface: intra_pvg01
    ipv4:
      import_policy: full
      export_policy: full
    ipv6:
      import_policy: full
      export_policy: full
