# Node: IEPL @ NoBrand Cloud
# https://cloud.nbdnet.com/
#
# Port mapping: 6400-6499
# tyo03-jp.ecs.iyoroy-infra.top:6400 -> 22
# :6433 -> pvg01

wireguard:
  default_private_key_ref: tyo03-jp/default
  interfaces:
  - name: intra_tyo01
    address:
    - fe80::2024:234/64
    listen_port: 10227
    table: 'off'
    peer:
      public_key: Sh62ZCxnEcXyLq49mLP1jF4C2vWKhKMxjtZHxVUAQg4=
      allowed_ips:
      - 0.0.0.0/0
      - ::/0
      endpoint: ipv4.tyo-jp.ecs.iyoroy-infra.top:10234
    post_up:
    - sysctl -w net.ipv6.conf.%i.autoconf=0
    fwmark: '4242'
  - name: intra_tyo02
    address:
    - fe80::2024:234/64
    listen_port: 10230
    table: 'off'
    peer:
      public_key: XMS2MhbgYyCZVhbiMsRwYGzpOky6GxmJOCM/NPqyuFQ=
      allowed_ips:
      - 0.0.0.0/0
      - ::/0
      endpoint: ipv4.tyo02-jp.ecs.iyoroy-infra.top:10234
    post_up:
    - sysctl -w net.ipv6.conf.%i.autoconf=0
  - name: intra_pvg01
    address:
    - fe80::2024:234/64
    listen_port: 6433
    table: 'off'
    peer:
      public_key: VdHU69ZeCaaq2V7Hg362YG+9dZ97DHYZxW0G7/Rs5FY=
      allowed_ips:
      - 0.0.0.0/0
      - ::/0
    post_up:
    - sysctl -w net.ipv6.conf.%i.autoconf=0
    fwmark: '4242'