iana:
  enabled: true
  upstreams:
  - protocol: iana_upstream_44324
    description: MoeDove
    neighbor:
      address: fc00:230::1
      asn: 44324
  downstreams: []
  peers:
  - protocol: iana_ix_203168
    description: Protocol 7 IX
    local: 2602:f92a:1315::1d
    neighbor:
      address: 2602:f92a:1315::1
      asn: 203168
  ibgp:
    enabled: false
    sessions: []
  static:
    advertise_routes:
    - IANA_OWNNETv6
    - IANA_AnycastNETv6
    extra_routes:
    - protocol: iana_static
      prefix: fc00:230::/64
      via:
        interface: eth0
      large_communities:
      - (205369,65535,65282)
  own_ipv6: 2a14:7583:f228::63f4
  own_net_v6: 2a14:7583:f220::/43
  own_netset_v6: '[ 2a14:7581:0ffb::/48+, 2a14:7583:f200::/40+ ]'
  router_id: 23.151.104.20
  allow_netset_v6: '[]'
