description: '@opkgbot'
asn: 4242420398
wireguard:
  public_key: QQecM/0eCbRu5TNdyRxGpJTCo6aGolMb0kZAqLH5Oho=
  listen_port: 20398
  fwmark: '4242'
  endpoint: nrt.dn42.boletus.icu:22024
lla: fe80::398
bgp:
  extended_next_hop: true
