description: http://dn42.baka.pub/
asn: 4242423374
wireguard:
  public_key: N7iQzqWLPb6lpRlf7grQG6rEzQOvDZWkmsRDkRnniH0=
  listen_port: 23374
  fwmark: '4242'
  endpoint: jp01.dn42.baka.pub:22024
lla: fe80::2999:226
bgp:
  extended_next_hop: true
