description: 22024 https://jp42.kskb.eu.org/autopeer/action_page.php
asn: 4242421817
wireguard:
  public_key: LDtwAj4hsCOmZEnAcb2uzOH5FP1q43ploOoG/8tDeC4=
  listen_port: 21817
  fwmark: '4242'
  endpoint: jp.kskb.eu.org:22024
lla: fe80::1817
bgp:
  extended_next_hop: true
