description: '@Sm1rkBot https://blog.bitrate.top/dn42'
asn: 4242423997
wireguard:
  public_key: wsjN0FgfZBFzSZQ66biOkYRtyQWWMFvX3ICOwj70D0U=
  listen_port: 23997
  fwmark: '4242'
  endpoint: jp1.dn42.bitrate.studio:22024
lla: fe80::3997
bgp:
  extended_next_hop: true
