description: '@moenetdn42bot'
asn: 4242420998
wireguard:
  public_key: OkZGn8FGwUNuC9pt3kYIFeDNIx/wsGGEWikfOsBDFl8=
  listen_port: 20998
  fwmark: '4242'
  endpoint: jp1.dn42.moenet.work:32024
lla: fe80::998:101:1:1
bgp:
  extended_next_hop: true
