render_root: '{{ inventory_dir }}/../.rendered'
dn42_global:
  own_as: 4242422024
  own_net: 172.20.234.224/28
  own_net_v6: fd18:3e15:61d0::/48
  own_netset: '[ 172.20.234.224/28+ ]'
  own_netset_v6: '[ fd18:3e15:61d0::/48+ ]'
iana_global:
  own_as: 205369
  anycast_net_v6: 2a14:7581:0ffb::/48
  own_netset_v6: '[ 2a14:7581:0ffb::/48+, 2a14:7583:f200::/40+, 2a14:67c3:fff0::/44+, 2a14:67c3:c0::/44+ ]'
  allow_netset_v6: '[]'
intra_global:
  confederation_start: 4220240000
  confederation_end: 4220249999
  prefix_v4: '[ 100.64.0.0/16+ ]'
  prefix_v6: '[ fd18:3e15:61d0:ffff::/64+ ]'
  loopback_v6_prefix: fd18:3e15:61d0:ffff
  link_local_prefix: fe80::2024
  confederation_as_format: '422024%d%d%02d'
  underlay_loopback_communities:
    - [4242422024, 1, 1]
    - [4242422024, 2, 0]
    - [4242422024, 2, 100]
    - [4242422024, 65535, 65281]
    - [65535, 65281]
  dn42_overlay_route_communities:
    - [4242422024, 1, 1]
    - [4242422024, 2, 100]
    - [4242422024, 65535, 65281]
    - [65535, 65281]
  iana_overlay_route_communities:
    - [205369, 1, 1]
    - [205369, 2, 100]
    - [205369, 65535, 65281]
    - [65535, 65281]

bird_deploy:
  remote_dir: /etc/bird
  staging_parent: /var/tmp/bird2-configuration
  backup_parent: /var/backups/bird2-configuration
  check_command: bird -p -c bird.conf
  reload_command: birdc configure
  secrets_file: '{{ inventory_dir }}/secrets/bird.yml'
  preserve_patterns:
    - secrets.conf

wireguard_deploy:
  enabled: false
  local_root: '{{ inventory_dir }}/../wireguard'
  render_root: '{{ inventory_dir }}/../.rendered-wireguard'
  remote_dir: /etc/wireguard
  staging_parent: /var/tmp/bird2-configuration-wireguard
  backup_parent: /var/backups/bird2-configuration-wireguard
  secrets_file: '{{ inventory_dir }}/secrets/wireguard.yml'

dn42_wireguard_defaults:
  address:
    - fe80::2024/64
  allowed_ips:
    - 10.0.0.0/8
    - 172.20.0.0/14
    - 172.31.0.0/16
    - fd00::/8
    - fe00::/8
  table: 'off'
  post_up:
    - sysctl -w net.ipv6.conf.%i.autoconf=0

intra_wireguard_defaults:
  address_mode: intra_local
  allowed_ips:
    - 0.0.0.0/0
    - ::/0
  table: 'off'
  post_up:
    - sysctl -w net.ipv6.conf.%i.autoconf=0
