function is_self_iana_v6() { 
    return net ~ IANA_OWNNETSETv6;
}

function iana_should_export(){
    if !(bgp_large_community ~ [(205369,2000,1)]) then
        return false;

    if bgp_large_community ~ [(205369,2000,666)] then
        return false;
    
    return true;
}