function is_self_iana_v6() { 
    return net ~ IANA_OWNNETSETv6;
}

function iana_filter_default_check(){
    if roa_check(iana_roa_v6, net, bgp_path.last) = ROA_INVALID then return false;
    if net ~ [::/0] then return false;
    if net.len > 48 then return false;
    return true;
}