function iana_peer_add_community(){
    bgp_large_community.add((205369,1,1)); # control: allow route to be advertised on IANA infrastructures
    bgp_large_community.add((205369,2,101)); # origin identify: from peer
}

function iana_peer_check_community(){
    if !(bgp_large_community ~ [(205369,1,1)]) then return false; # control: allow to be advertised on IANA infrastructures
    if bgp_large_community ~ [(205369,65535,65282)] then return false; # control: no-advertise
    if bgp_large_community ~ [(205369,65535,65281)] then return false; # control: no-export

    if bgp_large_community ~ [(205369,2,0)] then return false; # origin identify: private network
    if bgp_large_community ~ [(205369,2,101)] then return false; # origin identify: from peer
    if bgp_large_community ~ [(205369,2,102)] then return false; # origin identify: from upstream

    return true;
}

template bgp iana_peer{
    router id IANA_ROUTER_ID;
    local as IANA_OWNAS;
    ipv6 {
        import filter {
            if !iana_filter_default_check() then reject;
            iana_peer_add_community();
            accept;
        };
        export filter {
            if !iana_filter_default_check() then reject;
            if !iana_peer_check_community() then reject;
            remove_confederation_as();
            remove_private_community();
            accept;
        };
    };
    graceful restart;
}

protocol bgp 'iana_ix_zxix_rs1' from iana_peer{
    local 2406:840:1f:1000::20:5369:1;
    neighbor 2406:840:1f:1000::1 as 140961;
}

protocol bgp 'iana_ix_zxix_rs2' from iana_peer{
    local 2406:840:1f:1000::20:5369:1;
    neighbor 2406:840:1f:1000::2 as 140961;
}

protocol bgp 'iana_ix_akix' from iana_peer{
    local 2602:f92a:1315:2::34;
    neighbor 2602:f92a:1315:2::1 as 203168;
}
