template bgp iana_peer{
    router id IANA_ROUTER_ID;
    local as IANA_OWNAS;
    ipv6 {
        import filter {
            if net ~ [::/0] then reject;
            if bgp_path.len > 2 then reject;
            accept;
        };
        export filter {
            if is_self_iana_v6() then accept;
            accept;
        };
    };
    graceful restart;
}