roa4 table iana_roa;
roa6 table iana_roa_v6;

protocol rpki iana_rpki_cloudflare {
    roa4 { table iana_roa; };
    roa6 { table iana_roa_v6; };
    remote "rtr.rpki.cloudflare.com" port 8282;
    
    retry keep 5;
    refresh keep 1800;
    expire keep 7200;
}
