protocol static iana_static_advertise{
    route IANA_OWNNETv6 reject;
    route IANA_AnycastNETv6 reject;

    ipv6 {
        import filter{
            bgp_large_community.add((205369,1,1)); # control: allow route to be advertised on IANA infrastructures
            bgp_large_community.add((205369,2,100)); # origin identify: from downstream
            # consider our own prefix as customer and treat as downstream
            accept;
        };
        export none;
    };
}