protocol static iana_static_advertise{
    route IANA_OWNNETv6 reject;
    route IANA_AnycastNETv6 reject;

    ipv6 {
        import filter{
            bgp_large_community.add((205369,1000,205369));
            bgp_large_community.add((205369,2000,1));
            accept;
        };
        export none;
    };
}