template bgp iana_upstream {
    local as IANA_OWNAS;
    path metric 1;
    router id IANA_ROUTER_ID;

    ipv6 {
        import filter {
            if net ~ [::/0] then reject;
            krt_prefsrc = IANA_OWNIPv6;
            bgp_large_community.add((205369,1000,1));
            bgp_large_community.add((205369,2000,2));
            accept;
        };
        export filter {
            if is_self_iana_v6() then{
                if !iana_should_export() then reject;
                remove_confederation_as();
                remove_private_community();
                accept;
            }
            reject;
        };
        export limit 10;
    };

    graceful restart; 
}

protocol bgp 'iana_upstream_44324' from iana_upstream{
    description "MoeDove";
    neighbor fc00:32e0::1 as 44324;
}

