bird:
  log_syslog_all: false
  device_scan_time: 10
  device_semicolon: false
  include_sections:
  - - path: filter.conf
  - - path: iana/rpki.conf
    - path: iana/filter.conf
    - path: iana/static.conf
    - path: iana/upstream.conf
    - path: iana/peer.conf
    - path: iana/ibgp.conf
  - - path: dn42/rpki.conf
    - path: dn42/filter.conf
    - path: dn42/flapalerted.conf
    - path: dn42/static.conf
    - path: dn42/ebgp.conf
  - - path: intra/filter.conf
    - path: intra/ibgp.conf
    - path: intra/static.conf
  - - path: kernel.conf
modules:
  iana:
    enabled: true
    includes:
    - rpki.conf
    - filter.conf
    - static.conf
    - upstream.conf
    - peer.conf
    - ibgp.conf
  dn42:
    enabled: true
    includes:
    - filter.conf
    - flapalerted.conf
    - static.conf
    - rpki.conf
    - ebgp.conf
  intra:
    enabled: true
    includes:
    - filter.conf
    - ibgp.conf
    - static.conf
intra:
  own_as: 4220240004
  router_id: DN42_OWNIP
  static:
    v4_routes:
    - prefix: 172.20.234.228/32
      communities:
      - [4242422024, 1, 1]
      - [4242422024, 2, 0]
      - [4242422024, 2, 100]
      - [4242422024, 65535, 65281]
    v6_routes:
    - prefix: fd18:3e15:61d0::4/128
      communities:
      - [4242422024, 1, 1]
      - [4242422024, 2, 0]
      - [4242422024, 2, 100]
      - [4242422024, 65535, 65281]
  ibgp_sessions:
  - file: fra02.conf
    protocol: intra_ibgp_fra02
    neighbor:
      address: fe80::2024:1
      interface: intra_fra02
  - file: lax.conf
    protocol: intra_ibgp_lax
    neighbor:
      address: fe80::2024:229
      interface: intra_lax
  - file: tyo.conf
    protocol: intra_ibgp_tyo
    neighbor:
      address: fe80::2024:227
      interface: intra_tyo
