dn42:
  own_ip: 172.20.234.228
  own_ipv6: fd18:3e15:61d0::4
  region: 41
  country: 1276
  flapalerted:
    local: 172.20.234.228
    neighbor:
      address: 172.20.234.227
      port: 1790
    rpki_remote:
      address: 172.20.234.227
      port: 8083
  peers: []
  ix:
    sessions: []
