iana:
  enabled: true
  upstreams:
  - protocol: iana_upstream_64515
    description: Vultr
    neighbor:
      address: 2001:19f0:ffff::1
      asn: 64515
    multihop: 2
    password_ref: fra01_iana_upstream_64515
  downstreams: []
  peers: []
  ibgp:
    enabled: false
    sessions: []
  static:
    advertise_routes:
    - IANA_OWNNETv6
    - IANA_AnycastNETv6
    extra_routes:
    - protocol: iana_static
      prefix: 2001:19f0:ffff::1/128
      via:
        address: fe80::fc00:6ff:fe3c:d801
        interface: enp1s0
      communities:
      - (205369,65535,65282)
  own_ipv6: 2a14:7583:f244::3b06
  own_net_v6: 2a14:7583:f244::/48
  own_netset_v6: '[ 2a14:7581:0ffb::/48+, 2a14:7583:f200::/40+, 2a14:67c3:fff0::/44+,
    2a14:67c3:c0::/44+ ]'
  router_id: 80.240.31.71
  allow_netset_v6: '[]'