bird:
  log_syslog_all: false
  device_scan_time: 10
  device_semicolon: false
modules:
  iana:
    enabled: true
    includes:
    - rpki.conf
    - filter.conf
    - static.conf
    - upstream.conf
    - peer.conf
    - downstream.conf
    - ibgp.conf
  dn42:
    enabled: true
    includes:
    - filter.conf
    - flapalerted.conf
    - static.conf
    - rpki.conf
    - ebgp.conf
  intra:
    enabled: true
    includes:
    - filter.conf
    - ibgp.conf
    - static.conf
intra:
  static:
    v4_routes:
    - prefix: 172.20.234.228/32
    v6_routes:
    - prefix: fd18:3e15:61d0::4/128
    - prefix: 2a14:7583:f244::3b06/128
