intra_peers:
- node: fra02-de
  interface: intra_fra02
  wireguard:
    public_key: m7HQia4TdZB2vyI4ajcSlKv9Y/qbhsKiz+HDvsx6nno=
    listen_port: 10001
    address_mode: intra_local
  bgp:
    file: fra02.conf
    protocol: intra_ibgp_fra02
- node: lax01-us
  interface: intra_lax01
  wireguard:
    public_key: As0rZo5b9Bwt4loPGl6iSdtOqkd2p6ExK/Xyoy9OmTU=
    listen_port: 10229
    address_mode: intra_local
  bgp:
    file: lax01.conf
    protocol: intra_ibgp_lax01
- node: tyo01-jp
  interface: intra_tyo01
  wireguard:
    public_key: Sh62ZCxnEcXyLq49mLP1jF4C2vWKhKMxjtZHxVUAQg4=
    listen_port: 10227
    address_mode: intra_local
  bgp:
    file: tyo01.conf
    protocol: intra_ibgp_tyo01
