node:
  name: fra01-de
  tier: 1
  region: 2
  node_id: 1
  node_token: "3b06"
  peering:
    enabled: true
deploy:
  service_manager: systemd
  bird:
    enabled: true
  wireguard:
    enabled: true
