wireguard:
  default_private_key_ref: hkg03-cn/default
  interfaces:
  - name: intra_hkg02
    address:
    - fe80::2024:2/64
    listen_port: 10225
    table: 'off'
    peer:
      public_key: bg+KnzVupBrOQntHFFVzvBx+3sqYVoyJRantT6m5fm8=
      allowed_ips:
      - 0.0.0.0/0
      - ::/0
      endpoint: ipv4.hkg02-cn.ecs.iyoroy-infra.top:10002
    post_up:
    - sysctl -w net.ipv6.conf.%i.autoconf=0
    fwmark: '4242'