bird:
  log_syslog_all: true
  device_scan_time: 10
  device_semicolon: true
modules:
  iana:
    enabled: true
    includes:
    - rpki.conf
    - filter.conf
    - static.conf
    - upstream.conf
    - peer.conf
    - downstream.conf
    - ibgp.conf
  dn42:
    enabled: true
    includes:
    - rpki.conf
    - filter.conf
    - flapalerted.conf
    - static.conf
    - ebgp.conf
  intra:
    enabled: true
    includes:
    - filter.conf
    - ibgp.conf
    - static.conf
intra:
  static:
    v4_routes:
    - prefix: 172.20.234.233/32
      communities:
      - [4242422024, 1, 1]
      - [4242422024, 2, 0]
      - [4242422024, 2, 100]
      - [4242422024, 65535, 65281]
      - [65535, 65281]
    v6_routes:
    - prefix: fd18:3e15:61d0::9/128
      communities:
      - [4242422024, 1, 1]
      - [4242422024, 2, 0]
      - [4242422024, 2, 100]
      - [4242422024, 65535, 65281]
      - [65535, 65281]
    - prefix: 2a14:7583:f22d:2000::5fac/128
      communities:
      - [205369, 1, 1]
      - [205369, 2, 0]
      - [205369, 2, 100]
      - [205369, 65535, 65281]
      - [65535, 65281]
  ibgp_sessions:
  - file: tyo03.conf
    protocol: intra_ibgp_tyo03
    neighbor:
      node: tyo03-jp
      interface: intra_tyo03
    ipv4:
      import_policy: full
      export_policy: full
    ipv6:
      import_policy: full
      export_policy: full
  - file: pvg_82b4.conf
    protocol: intra_ibgp_pvg_82b4
    local_as: 4220240005
    neighbor:
      address: fe80::82b4
      interface: intra_pvg_82b4
    ipv4:
      import_policy: iana_full
      export_policy: iana_full
    ipv6:
      import_policy: iana_full
      export_policy: iana_full
  - file: hkg04.conf
    protocol: intra_ibgp_hkg04
    neighbor:
      node: hkg04-hk
      interface: intra_hkg04
    ipv4:
      import_policy: full
      export_policy: full
    ipv6:
      import_policy: full
      export_policy: full
