iana:
  enabled: true
  upstreams4: []
  upstreams6: []
  downstreams: []
  peers: []
  ibgp:
    enabled: false
    sessions: []
  ibgp:
    enabled: false
    sessions: []
  static:
    advertise_routes:
    - "2a14:67c3:fff0::/44"
    extra_routes: []
  own_ipv6: 2a14:67c3:fff0::3513
  own_net_v6: 2a14:67c3:fff0::/44
  own_netset_v6: '[ 2a14:7581:0ffb::/48+, 2a14:7583:f200::/40+, 2a14:67c3:fff0::/44+,
    2a14:67c3:c0::/44+ ]'
  router_id: 23.149.120.51
  allow_netset_v6: '[]'
