bird:
  log_syslog_all: true
  device_scan_time: 10
  device_semicolon: true
modules:
  iana:
    enabled: true
    includes:
    - rpki.conf
    - filter.conf
    - static.conf
    - upstream.conf
    - peer.conf
    - downstream.conf
    - ibgp.conf
  dn42:
    enabled: true
    includes:
    - rpki.conf
    - filter.conf
    - flapalerted.conf
    - static.conf
    - ebgp.conf
  intra:
    enabled: true
    includes:
    - filter.conf
    - ibgp.conf
    - static.conf
intra:
  static:
    v4_routes:
    - prefix: 172.20.234.233/32
    v6_routes:
    - prefix: fd18:3e15:61d0::9/128
    - prefix: 2a14:7583:f22d:2000::5fac/128
  ibgp_sessions:
  - file: pvg_82b4.conf
    protocol: intra_ibgp_pvg_82b4
    local_as: 4220240005
    neighbor:
      address: fe80::82b4
      interface: intra_pvg_82b4
    ipv4:
      import_policy: iana_full
      export_policy: iana_full
    ipv6:
      import_policy: iana_full
      export_policy: iana_full
