iana:
  enabled: true
  upstreams4: []
  upstreams6: []
  downstreams: []
  peers: []
  ibgp:
    enabled: false
    sessions: []
  static:
    advertise_routes:
    - "2a14:7583:f22d:2000::/56"
    extra_routes: []
  own_ipv6: 2a14:7583:f22d:2000::5fac
  own_net_v6: 2a14:7583:f22d:2000::/56
  router_id: 23.149.120.51
