intra:
  auto_confed_peers:
    - node: hkg04-hk
      interface: intra_hkg04
      wireguard:
        public_key: 1tn6T2xi+zEnNi8X7ssGH9M3WOeq1xDjZNX3mMkO7Qk=
        listen_port: 10235
        persistent_keepalive: 30
        fwmark: '4242'
      bgp:
        file: hkg04.conf
        protocol: intra_ibgp_hkg04
        ipv4:
          import_policy: full
          export_policy: full
        ipv6:
          import_policy: full
          export_policy: full
    - node: tyo03-jp
      interface: intra_tyo03
      wireguard:
        public_key: lCx0qzITDvh2ZIfNppOttFnKFa16fCqDGn7mWufMzGE=
        listen_port: 10234
        fwmark: '4242'
        address_mode: intra_local
        persistent_keepalive: 30
      bgp:
        file: tyo03.conf
        protocol: intra_ibgp_tyo03
        ipv4:
          import_policy: full
          export_policy: full
        ipv6:
          import_policy: full
          export_policy: full

  explicit_confed_peers:
    - file: pvg_82b4.conf
      protocol: intra_ibgp_pvg_82b4
      local_as: 4220240005
      neighbor:
        address: fe80::82b4
        interface: intra_pvg_82b4
      ipv4:
        import_policy: iana_full
        export_policy: iana_full
      ipv6:
        import_policy: iana_full
        export_policy: iana_full
