dn42:
  own_ip: 172.20.234.225
  own_ipv6: fd18:3e15:61d0::1
  region: 52
  country: 1344
  flapalerted:
    local: 172.20.234.225
    neighbor:
      address: 172.20.234.232
      port: 1790
    rpki_remote:
      address: 172.20.234.232
      port: 8083
  peers:
  - description: '@iu_yang1 https://blog.begalaxy.top/index.php/38.html'
    neighbor:
      address: fe80::1836
    asn: 4201273722
    wireguard:
      public_key: S8BzQtSgHy+YFnnBjE0bmBYDIvCve5Tv43Y2dcVVBm4=
      listen_port: 33722
      fwmark: '4242'
      endpoint: sg1.dn42.begalaxy.top:22024
    lla: fe80::1836
    bgp:
      extended_next_hop: true
  - description: '@MadobiNanami https://blog.nanami.tech/'
    neighbor:
      address: fe80::55
    asn: 4242420055
    wireguard:
      public_key: ifY8fh4xZuIVF10FJ5PYnJBkN/NuMpLscK5serYUfBw=
      listen_port: 20055
      fwmark: '4242'
      endpoint: 45.196.219.99:22024
    lla: fe80::55
    bgp:
      extended_next_hop: true
  - description: '@Lie_Kong https://blog.lie-kong.top/dn42/'
    neighbor:
      address: fe80::70:2
    asn: 4242420070
    wireguard:
      public_key: 3Qhit0K7maW6oMVt57KUkWDiDfZ/OWOYwzu/fYrk6iE=
      listen_port: 20070
      fwmark: '4242'
      endpoint: 31.42.125.144:22024
    lla: fe80::70:2
    bgp:
      extended_next_hop: true
  - description: '@linmontfurry'
    neighbor:
      address: fe80::88
    asn: 4242420088
    wireguard:
      public_key: kDkJLZbrW6PWXeTJEVRWKwPpv+wsnsNthW0nDDGtMhg=
      listen_port: 20088
      fwmark: '4242'
      private_key_ref: hkg02-cn/dn42_4242420088
      endpoint: 46.20.109.97:22024
    lla: fe80::88
    bgp:
      extended_next_hop: true
  - description: https://sdubs.vip
    neighbor:
      address: fe80::202:2
    asn: 4242420202
    wireguard:
      public_key: 5YcwL93bhJqzhTxi9b1Z1ZRt2UfGVoP5jMA+UXma6HM=
      listen_port: 20202
      fwmark: '4242'
      private_key_ref: hkg02-cn/dn42_4242420202
      endpoint: dn02.hk.hk.sdubs.vip:22024
    lla: fe80::202:2
    bgp:
      extended_next_hop: true
  - description: '@ZeroWolf233 https://zerowolf.cn/dn42/'
    neighbor:
      address: fe80::233
    asn: 4242420233
    wireguard:
      public_key: bWUSnkOds7fUAw/hh30QaORMjPi4+/PRWY8+AgqC6UU=
      listen_port: 20233
      fwmark: '4242'
      endpoint: hk2.0l.ink:22024
    lla: fe80::233
    bgp:
      extended_next_hop: true
  - description: '@Nuro_Atamashino'
    neighbor:
      address: fe80::298
    asn: 4242420298
    wireguard:
      public_key: v0tF03d5jK/t6hjRnOv5ddTkTxzja9HSc8SWbCQ+WzI=
      listen_port: 20298
      fwmark: '4242'
      private_key_ref: hkg02-cn/dn42_4242420298
      endpoint: node2.ox5.cc:22024
    lla: fe80::298
    bgp:
      extended_next_hop: true
  - description: '@zxxwdd'
    neighbor:
      address: fe80::337
    asn: 4242420337
    wireguard:
      public_key: WdvyDf+lEAar5MbcFYUVhvQXzWg2ZXi9Jt1860Q41y4=
      listen_port: 20337
      fwmark: '4242'
      endpoint: hkg02.dn42.wwrr.ru:22024
    lla: fe80::337
    bgp:
      extended_next_hop: true
  - description: '@Alice_8585'
    neighbor:
      address: fe80::387
    asn: 4242420387
    wireguard:
      public_key: krJb3l8hypXbDs8h6zNw5QQy5zdwVsRKRm1g30KnYBU=
      listen_port: 20387
      fwmark: '4242'
      endpoint: 156.226.173.78:22024
    lla: fe80::387
    bgp:
      extended_next_hop: true
  - description: '@opkgbot'
    lla: fe80::398
    bgp:
      extended_next_hop: true
    asn: 4242420398
    wireguard:
      public_key: XD66eoHp06VmDUNFUguJeOY8gFLiLZ7Lkyz/WsMQSWU=
      listen_port: 20398
      endpoint: hkl.dn42.boletus.icu:22024
      fwmark: '4242'
  - description: '@Virtual0PTR https://blog.0xptr.top/en/about/dn42_peering'
    neighbor:
      address: fe80::d555
    asn: 4242420555
    wireguard:
      public_key: xin3e9mT1MVzPUVGG7pVIZ/FIkwOIGQNN2cVpCTLNS8=
      listen_port: 20555
      fwmark: '4242'
      endpoint: 45.87.102.60:22024
    lla: fe80::d555
    bgp:
      extended_next_hop: true
  - description: '@v3tianyi'
    neighbor:
      address: fe80::712
    asn: 4242420712
    wireguard:
      public_key: EdTexGeX46urgHTnPJYCRyRI5kV4h/jTPpN2JQKYXXo=
      listen_port: 20712
      fwmark: '4242'
      endpoint: dn42.hkg6.luotianyi.us:22024
    lla: fe80::712
    bgp:
      extended_next_hop: true
  - description: '@Iridoideae'
    neighbor:
      address: fe80::1023:2
    asn: 4242421023
    wireguard:
      public_key: dPTukyAM6scP2dlCYiP55BDb0lmuBhX7Rm4G8p/9awA=
      listen_port: 21023
      fwmark: '4242'
      endpoint: hkg-01.node.svc.moe:22024
    lla: fe80::1023:2
    bgp:
      extended_next_hop: true
  - description: '@jlu5ca https://highdef.network/'
    neighbor:
      address: fe80::1080:38
    asn: 4242421080
    wireguard:
      public_key: eedTHubyl5caiHH50GkknQa8SQtAF8q7aqmL26w5qSs=
      listen_port: 21080
      fwmark: '4242'
      private_key_ref: hkg02-cn/dn42_4242421080
      endpoint: hkg.peer.highdef.network:22024
    lla: fe80::1080:38
    bgp:
      extended_next_hop: true
  - description: '@antenna000 https://blog.yuyuko.com/post/7'
    neighbor:
      address: fe80::1117
    asn: 4242421117
    wireguard:
      public_key: gqwdC9p6jdSy80oRxdatr9QdSrNMLCvRMadaCeOBqDY=
      listen_port: 21117
      fwmark: '4242'
      endpoint: hk01.dn42.yuyuko.com:22024
    lla: fe80::1117
    bgp:
      extended_next_hop: true
  - description: '@Ximiawa_bot @Mxmilu https://milu.ink/dn42'
    neighbor:
      address: fe80::1166
    asn: 4242421166
    wireguard:
      public_key: f9ZDh2U0UXxtEroHUYNWzaE6TZM3hhY3eLXQQpgkvBY=
      listen_port: 21166
      fwmark: '4242'
      private_key_ref: hkg02-cn/dn42_4242421166
      endpoint: hk.dn42.milu.moe:22024
    lla: fe80::1166
    bgp:
      extended_next_hop: true
  - description: '@pfxlabs https://prefixlabs.net/'
    neighbor:
      address: fe80::1240:7
    asn: 4242421240
    wireguard:
      public_key: FzWgCU4/y4pyGibDF5UYS13LvDCQ3569uNZJRUEIXiI=
      listen_port: 21240
      fwmark: '4242'
      endpoint: 160.191.224.89:22024
    lla: fe80::1240:7
    bgp:
      extended_next_hop: true
  - description: '@BIGGER_THAN_SHIT'
    neighbor:
      address: fe80::9527
    asn: 4242421260
    wireguard:
      public_key: 9zsuhOiSC8rKsdUNtX678wh3rTo4McJ9ueDqm1Ha8wI=
      listen_port: 21260
      fwmark: '4242'
      endpoint: 405218.xyz:60113
    lla: fe80::9527
    bgp:
      extended_next_hop: true
  - description: '@Xeri_Xeiu https://blog.xeiu.top/dn42-info'
    neighbor:
      address: fe80::3:1336
    asn: 4242421336
    wireguard:
      public_key: HZwPJ/2RK9UDePLUSFLeB6LWdKMcmPVoGz/9qPHFcwY=
      listen_port: 21336
      fwmark: '4242'
      endpoint: hk2.dn42.xeiu.top:22024
    lla: fe80::3:1336
    bgp:
      extended_next_hop: true
  - description: '@DictXiong https://beardic.cn/zh-cn/dn42/'
    neighbor:
      address: fe80::1366
    asn: 4242421366
    wireguard:
      public_key: EoPA+dH5xxHwUYCVpe/3afL0qQp5SQB7b2OHD8nrB30=
      listen_port: 21366
      fwmark: '4242'
      endpoint: hk0.dxng.net:22024
    lla: fe80::1366
    bgp:
      extended_next_hop: true
  - description: https://dn42.guet.eu.org/zh-cn/contact/
    neighbor:
      address: fe80::1686
    asn: 4242421686
    wireguard:
      public_key: D4MBIR+HsCPeEGuPg1YziRe1RgaG7jaiTw4wmV8XZUY=
      listen_port: 21686
      fwmark: '4242'
      endpoint: hk-1.dn42.guet.eu.org:22024
    lla: fe80::1686
    bgp:
      extended_next_hop: true
  - description: '@messageleaf https://exploro.one/dn42'
    neighbor:
      address: fe80::5ec6:ff37:aec1:d0ab
    asn: 4242421771
    wireguard:
      public_key: vKIhFMvKHDVEcRls1IH7si2MSia73H3lsXAWrrC+5zU=
      listen_port: 21771
      fwmark: '4242'
      endpoint: 205.198.65.116:40004
    lla: fe80::5ec6:ff37:aec1:d0ab
    bgp:
      extended_next_hop: true
  - description: '@Potat0_DN42_Bot'
    neighbor:
      address: fe80::1816
    asn: 4242421816
    wireguard:
      public_key: Tv1+HniELrS4Br2i7oQgwqBJFXQKculsW8r+UOqQXH0=
      listen_port: 21816
      fwmark: '4242'
      private_key_ref: hkg02-cn/dn42_4242421816
      endpoint: 103.213.4.37:22024
    lla: fe80::1816
    bgp:
      extended_next_hop: true
  - description: '@imlonghao'
    neighbor:
      address: fe80::1888
    asn: 4242421888
    wireguard:
      public_key: RyP2/n///CanKOD1EFtiPawHfUZb14+Fg0v4pbpsrnY=
      listen_port: 21888
      fwmark: '4242'
      endpoint: 154.3.37.101:22024
    lla: fe80::1888
    bgp:
      extended_next_hop: true
  - description: https://luotianyi.eu/dn42/
    neighbor:
      address: fe80::1999
    asn: 4242421999
    wireguard:
      public_key: DFXS1z5X3SWfGioSTicV9dPpEgD0HiuFvpfFPQD79QY=
      listen_port: 21999
      fwmark: '4242'
      endpoint: hk2.v6.dn42.luotianyi.sbs:22024
    lla: fe80::1999
    bgp:
      extended_next_hop: true
  - description: '@butlanys'
    neighbor:
      address: fe80::2018
    asn: 4242422018
    wireguard:
      public_key: J8LY0vaOzaxH1k3Qrhjv7/U3ATj5B29HwgmednA5rUI=
      listen_port: 22018
      fwmark: '4242'
      endpoint: xiaobai.hkg.butlanys.de:22024
    lla: fe80::2018
    bgp:
      extended_next_hop: true
  - description: wyf@932686.xyz https://blog.wolfyang.fan/notes/dn42
    neighbor:
      address: fe80::2034
    asn: 4242422034
    wireguard:
      public_key: JMk8ABRFTEjyNFXMgT0ti3RwtH6ciaFn3lmXVmsShj0=
      listen_port: 22034
      fwmark: '4242'
      endpoint: a1.932.moe:22024
    lla: fe80::2034
    bgp:
      extended_next_hop: true
  - description: '@izmimz'
    neighbor:
      address: fe80::2164
    asn: 4242422164
    wireguard:
      public_key: B0QyNLwiqaCY9/ar8556/a2+x37lplzVOHbvd8Qyg04=
      listen_port: 22164
      fwmark: '4242'
      endpoint: hk.dn42.izm.im:32024
    lla: fe80::2164
    bgp:
      extended_next_hop: true
  - description: https://iedon.net
    neighbor:
      address: fe80::2189:120
    asn: 4242422189
    wireguard:
      public_key: OlUDuWkUI9pKNsNo7Vjf/GKKVSBslh9kmqjbeYA4+34=
      listen_port: 22189
      fwmark: '4242'
      private_key_ref: hkg02-cn/dn42_4242422189
      endpoint: hk-hkg.dn42.iedon.net:60395
    lla: fe80::2189:120
    bgp:
      extended_next_hop: true
  - description: https://peering.maraun.de/
    neighbor:
      address: fe80::2225
    asn: 4242422225
    wireguard:
      public_key: rWTIK93+XJaP4sRvrk1gqXxAZgkz6y/axLC4mjuay1I=
      listen_port: 22225
      fwmark: '4242'
      endpoint: dn42-sg.maraun.de:22024
    lla: fe80::2225
    bgp:
      extended_next_hop: true
  - description: '@moohric https://www.mhr.hk/posts/dn42-peering/'
    neighbor:
      address: fe80::2279
    asn: 4242422279
    wireguard:
      public_key: PUjqyQ3ATLp8Cxp3YFVQ44QLoZEpoPgdXsbMfXhDMRk=
      listen_port: 22279
      fwmark: '4242'
      endpoint: hk-hkg1.bb.mhr.hk:22024
    lla: fe80::2279
    bgp:
      extended_next_hop: true
  - description: '@SessX6cf https://dn42.xhustudio.eu.org/peering.html'
    neighbor:
      address: fe80::2466
    asn: 4242422466
    wireguard:
      public_key: 25F5Kt0fg7bTien58apDN2dLUyCN2DSe7W+Nvw7eCT4=
      listen_port: 22466
      fwmark: '4242'
      mtu: 1492
      endpoint: v4.hydrogen.xhustudio.eu.org:22024
    lla: fe80::2466
    bgp:
      extended_next_hop: true
  - description: '@unstartdev https://unstartdev.eu.org/dn42'
    neighbor:
      address: fe80::2467
    asn: 4242422467
    wireguard:
      public_key: N6QLB7m3ZDmsTNoXIGm+LlrTqou4mfH9zTgRy83XMwU=
      listen_port: 22467
      fwmark: '4242'
      endpoint: 45.149.92.55:22024
    lla: fe80::2467
    bgp:
      extended_next_hop: true
  - description: '@samandjyf1 https://blog.sam1314.com/DN42/'
    neighbor:
      address: fe80::2503
    asn: 4242422503
    wireguard:
      public_key: GyS7yHeu3kQykROMr6ZMix8FRUlLE/mxQWmn1zzdAUE=
      listen_port: 22503
      fwmark: '4242'
      endpoint: 156.248.8.4:22024
    lla: fe80::2503
    bgp:
      extended_next_hop: true
  - description: https://lantian.pub
    neighbor:
      address: fe80::2547
    asn: 4242422547
    wireguard:
      public_key: xelzwt1j0aoKjsQnnq8jMjZNLbLucBPwPTvHgFH/czs=
      listen_port: 22547
      fwmark: '4242'
      private_key_ref: hkg02-cn/dn42_4242422547
      endpoint: v4.v-ps-hkg.lantian.pub:22024
    lla: fe80::2547
    bgp:
      extended_next_hop: true
  - description: https://peer.dn42.6700.cc
    neighbor:
      address: fe80::3088:192
    asn: 4242423088
    wireguard:
      public_key: rBTH+JyZB0X/DkwHByrCjCojxBKr/kEOm1dTAFGHR1w=
      listen_port: 23088
      fwmark: '4242'
      private_key_ref: hkg02-cn/dn42_4242423088
      endpoint: hk1-hk.dn42.6700.cc:22024
    lla: fe80::3088:192
    bgp:
      extended_next_hop: true
  - description: '@Grayowo'
    neighbor:
      address: fe80::3101:2
    asn: 4242423101
    wireguard:
      public_key: P/OvJv/XcCkOaA7/+UEx2Q2SsxmO/BvbsTTwZcUuXTo=
      listen_port: 23101
      fwmark: '4242'
      endpoint: 47.84.117.221:22024
    lla: fe80::3101:2
    bgp:
      extended_next_hop: true
  - description: AS10099@foxmail.com @WOW55999 https://dn42.gtio.de/
    neighbor:
      address: fe80::2:3128
    asn: 4242423128
    wireguard:
      public_key: rJzBhEpXkPoEgb1SL13srNQPQOypb0GRCDudYAASAHc=
      listen_port: 23128
      fwmark: '4242'
      endpoint: dn42.hk.peer.gtio.de:22024
    lla: fe80::2:3128
    bgp:
      extended_next_hop: true
  - description: '@Auride'
    neighbor:
      address: fe80::2024:3310
    asn: 4242423310
    wireguard:
      public_key: aC9pjzMWZhbA/sLPljUFGU1K28MSopHbKNj5yyv4uzg=
      listen_port: 23310
      fwmark: '4242'
      endpoint: v4.hkg01.edge.r1.tmpfs.dev:22024
    lla: fe80::2024:3310
    bgp:
      extended_next_hop: true
  - description: '@Ykino233'
    neighbor:
      address: fe80::3311
    asn: 4242423311
    wireguard:
      public_key: qleh0csj45iN7ZM75kf3fDh0erMBJGABdvzM9BD0Byw=
      listen_port: 23311
      fwmark: '4242'
      endpoint: node01-bgp.hk.peakcomet.dpdns.org:22024
    lla: fe80::3311
    bgp:
      extended_next_hop: true
  - description: https://dn42.baka.pub/
    neighbor:
      address: fe80::2999:225
    asn: 4242423374
    wireguard:
      public_key: zcxhWeI3SrJtqlHuqdeNaCeWSwJIYOTjAraXm655+VY=
      listen_port: 23374
      fwmark: '4242'
      endpoint: hk01.dn42.baka.pub:22024
    lla: fe80::2999:225
    bgp:
      extended_next_hop: true
  - description: '@jack153376'
    neighbor:
      address: fe80::3376
    asn: 4242423376
    wireguard:
      public_key: tqDhZy2XJBzpctfVrwlTOccTrZFQSsaJn+5T2s0mU0s=
      listen_port: 23376
      fwmark: '4242'
      endpoint: 47.243.246.14:22024
    lla: fe80::3376
    bgp:
      extended_next_hop: true
  - description: '@LeZi9916'
    neighbor:
      address: fe80::3377
    asn: 4242423377
    wireguard:
      public_key: XaX6/G7EQbcjsrtlxNmDc/s/VSdTxtkBxZKB2JpWIHo=
      listen_port: 23377
      fwmark: '4242'
      private_key_ref: hkg02-cn/dn42_4242423377
      address:
      - fe80::2024/64
      - fe80::2053:69a/64
    lla: fe80::3377
    bgp:
      extended_next_hop: true
  - description: '@af9af584e050'
    neighbor:
      address: fe80::4242:4233:800d
    asn: 4242423380
    wireguard:
      public_key: UH/8wh7yFbkvhob4vuHm0y5fqqR6mCxu0fzsggLFxw8=
      listen_port: 23380
      fwmark: '4242'
      endpoint: 4.hk-akile.taroball.top:22024
    lla: fe80::4242:4233:800d
    bgp:
      extended_next_hop: true
  - description: '@winter_pm_bot'
    neighbor:
      address: fd4e:d0:d38d:68c1::1
    asn: 4242423658
    wireguard:
      public_key: L/ohOmR8NDe/sgaAI0md8RvT1lrPDZiLMny9QwLheAA=
      listen_port: 23658
      fwmark: '4242'
      endpoint: 82.152.165.157:22024
    lla: fd4e:d0:d38d:68c1::1
    bgp:
      extended_next_hop: true
  - description: '@tsy_ink'
    neighbor:
      address: fe80::3686
    asn: 4242423686
    wireguard:
      public_key: EhU7kTcbAzWPtII68A3lfzPaYjgcjuHEkMNtQrneDlY=
      listen_port: 23686
      fwmark: '4242'
      endpoint: vps-hk-hytorn.091014.xyz:22024
    lla: fe80::3686
    bgp:
      extended_next_hop: true
  - description: https://dn42.g-load.eu
    neighbor:
      address: fe80::ade0
    asn: 4242423914
    wireguard:
      public_key: sLbzTRr2gfLFb24NPzDOpy8j09Y6zI+a7NkeVMdVSR8=
      listen_port: 23914
      fwmark: '4242'
      endpoints:
      - 103.73.67.154:22024
      - hk1.g-load.eu:22024
    lla: fe80::ade0
    bgp:
      extended_next_hop: true
  - description: https://blog.sherpherd.net/dn42.html
    neighbor:
      address: fe80::3947:1
    asn: 4242423947
    wireguard:
      public_key: Lz/SPcnKfbp4Z6LW7gysFxhyJXfyoett18r3kvlZcBY=
      listen_port: 23947
      fwmark: '4242'
      endpoint: hk1.sherpherd.net:22024
    lla: fe80::3947:1
    bgp:
      extended_next_hop: true
  - description: '@Sm1rkBot https://blog.bitrate.top/dn42'
    neighbor:
      address: fe80::3997
    asn: 4242423997
    wireguard:
      public_key: BwDwBx+r7zTrUZHdUeKsQFkEVEgx4iH13+0LQnCtpEE=
      listen_port: 23997
      fwmark: '4242'
      endpoint: hk1.dn42.bitrate.studio:22024
    lla: fe80::3997
    bgp:
      extended_next_hop: true
  - description: '@charliemoomoo'
    neighbor:
      address: fe80::3999
    asn: 4242423999
    wireguard:
      public_key: mGGBczSVKW+7UKRquI2GkbKrfxiATv9r4uF5WTP+vWI=
      listen_port: 23999
      fwmark: '4242'
      endpoint: txg.node.cowgl.tech:32024
    lla: fe80::3999
    bgp:
      extended_next_hop: true
  ix:
    sessions: []
