intra:
  auto_confed_peers:
    - node: lax01-us
      interface: intra_lax01
      wireguard:
        public_key: As0rZo5b9Bwt4loPGl6iSdtOqkd2p6ExK/Xyoy9OmTU=
        listen_port: 10229
        fwmark: '4242'
        address_mode: intra_local
      bgp:
        file: lax01.conf
        protocol: intra_ibgp_lax01
        ipv4:
          import_policy: dn42_full
          export_policy: dn42_full
        ipv6:
          import_policy: dn42_full
          export_policy: dn42_full
    - node: cdg01-fr
      interface: intra_cdg01
      wireguard:
        public_key: vLZLdiJrDyGpUIY5y/qR5XIvyaWCcTM4uk9Y6kdIKk8=
        listen_port: 10123
        address_mode: intra_local
      bgp:
        file: cdg01.conf
        protocol: intra_ibgp_cdg01
    - node: tyo01-jp
      interface: intra_tyo01
      wireguard:
        public_key: Sh62ZCxnEcXyLq49mLP1jF4C2vWKhKMxjtZHxVUAQg4=
        listen_port: 10227
        fwmark: '4242'
        address_mode: intra_local
      bgp:
        file: tyo01.conf
        protocol: intra_ibgp_tyo01
        ipv4:
          import_policy: full
          export_policy: full
        ipv6:
          import_policy: full
          export_policy: full
    - node: hkg01-hk
      interface: intra_hkg01
      wireguard:
        public_key: p8K4/FOb+KjT96Xc9efqHbCp60sNefFf2kZSmokzDHs=
        listen_port: 10232
        fwmark: '4242'
        address_mode: intra_local
      bgp:
        file: hkg01.conf
        protocol: intra_ibgp_hkg01
        ipv4:
          import_policy: full
          export_policy: full
        ipv6:
          import_policy: full
          export_policy: full
    - node: hkg03-hk
      interface: intra_hkg03
      wireguard:
        public_key: gNiB+ZAfvxIthwuCLUxZ9QS/RYWyp0OW4rsdODm+NXc=
        listen_port: 10002
        fwmark: '4242'
        address_mode: intra_local
      bgp:
        file: hkg03.conf
        protocol: intra_ibgp_hkg03
        ipv4:
          import_policy: full
          export_policy: full
        ipv6:
          import_policy: full
          export_policy: full
    - node: hkg04-hk
      interface: intra_hkg04
      wireguard:
        public_key: 1tn6T2xi+zEnNi8X7ssGH9M3WOeq1xDjZNX3mMkO7Qk=
        listen_port: 10235
        fwmark: '4242'
        address_mode: intra_local
      bgp:
        file: hkg04.conf
        protocol: intra_ibgp_hkg04
        ipv4:
          import_policy: full
          export_policy: full
        ipv6:
          import_policy: full
          export_policy: full

  explicit_confed_peers:
    - file: hkg_9cce.conf
      protocol: intra_ibgp_hkg_9cce
      neighbor:
        address: fe80::2053:69b
        interface: dn42_4242423377
      ipv4:
        import_policy: iana_full
        export_policy: iana_full
      ipv6:
        import_policy: iana_full
        export_policy: iana_full
