node:
  name: hkg02-hk
  tier: 1
  region: 1
  node_id: 3
  node_token: "7d89"
  peering:
    enabled: true
deploy:
  service_manager: systemd
  bird:
    enabled: true
  wireguard:
    enabled: true
