wireguard:
  default_private_key_ref: hkg02-hk/default
  interfaces:
  - name: dn42_4242420014
    address:
    - fe80::2024/64
    listen_port: 20014
    table: 'off'
    peer:
      public_key: y5D4KE+anbxbZ8p+JvzqDRv+PY/FPAu+TD26/9bmYC0=
      allowed_ips:
      - 10.0.0.0/8
      - 172.20.0.0/14
      - 172.31.0.0/16
      - fd00::/8
      - fe00::/8
      endpoint: hk.dn42.fxnet.top:22024
    post_up:
    - sysctl -w net.ipv6.conf.%i.autoconf=0
    fwmark: '4242'
  - name: dn42_4242421817
    address:
    - fe80::2024/64
    listen_port: 21817
    table: 'off'
    peer:
      public_key: olXrGZKg3kKPdihHNfZ3zwwt+LPFQv9GMxLyA92fQl0=
      allowed_ips:
      - 10.0.0.0/8
      - 172.20.0.0/14
      - 172.31.0.0/16
      - fd00::/8
      - fe00::/8
      endpoint: 4.hk.kskb.eu.org:22024
    post_up:
    - sysctl -w net.ipv6.conf.%i.autoconf=0
    fwmark: '4242'
    private_key_ref: hkg02-hk/dn42_4242421817
  - name: intra_fra01
    address_mode: intra_local
    listen_port: 10228
    table: 'off'
    peer:
      public_key: 4zEFOrqHdIDPcjvu6NwbE1AAYBH1bA+SAowysX5fRT4=
      allowed_ips:
      - 0.0.0.0/0
      - ::/0
      endpoint: ipv6.fra01-de.ecs.iyoroy-infra.top:10225
    post_up:
    - sysctl -w net.ipv6.conf.%i.autoconf=0
    fwmark: '4242'
