template bgp dnpeers {
    router id DN42_OWNIP;
    local as DN42_OWNAS;
    path metric 1;

    ipv4 {
        table master4;
        import filter {
            if is_valid_dn42_network() && !is_self_dn42_net() then {
                if (roa_check(dn42_roa, net, bgp_path.last) != ROA_VALID) then {
                    print "[dn42] ROA check failed for ", net, " ASN ", bgp_path.last;
                    reject;
                }
                bgp_local_pref = dn42_ebgp_calculate_priority(); 
                bgp_large_community.add((205369,1000,42));
                bgp_large_community.add((205369,1101,COMMUNITY_NODE_ID));
                bgp_large_community.add((205369,2000,0));
                bgp_large_community.add((205369,2000,42));
                accept;
            }
            reject;
        };

        export filter {
            if is_valid_dn42_network() && source ~ [RTS_STATIC, RTS_BGP] then{ 
                if !dn42_should_export() then reject;
                if (roa_check(dn42_roa_flap_v4, net, bgp_path.last) = ROA_INVALID) then reject;
                if (is_self_dn42_net()) then {
                    bgp_community.add((64511, DN42_REGION));
                    bgp_community.add((64511, DN42_COUNTRY));
                }
                remove_confederation_as();
                remove_private_community();
                accept;
            }
            reject;
        };
    };

    ipv6 {
        table master6;
        import filter {
            if is_valid_dn42_network_v6() && !is_self_dn42_net_v6() then {
                if (roa_check(dn42_roa_v6, net, bgp_path.last) != ROA_VALID) then {
                    print "[dn42] ROA check failed for ", net, " ASN ", bgp_path.last;
                    reject;
                }
                bgp_local_pref = dn42_ebgp_calculate_priority(); 
                bgp_large_community.add((205369,1000,42));
                bgp_large_community.add((205369,1101,COMMUNITY_NODE_ID));
                bgp_large_community.add((205369,2000,0));
                bgp_large_community.add((205369,2000,42));
                accept;
            }
            reject;
        };
        export filter {
            if is_valid_dn42_network_v6() && source ~ [RTS_STATIC, RTS_BGP] then{ 
                if !dn42_should_export() then reject;
                if (roa_check(dn42_roa_flap_v6, net, bgp_path.last) = ROA_INVALID) then reject;
                if (is_self_dn42_net_v6()) then {
                    bgp_community.add((64511, DN42_REGION));
                    bgp_community.add((64511, DN42_COUNTRY));
                }
                remove_confederation_as();
                remove_private_community();
                accept;
            }
            reject;
        };
    };
}


include "peers/*";

