protocol static dn42_static_v4{
    route DN42_OWNNET reject;
    route 172.20.234.227/32 reject{
        bgp_large_community.add((4242422024,2,0)); # origin identify: private network
    };

    ipv4 {
        import filter{
            bgp_large_community.add((4242422024,1,1)); # control: allow route to be advertised on DN42 infrastructures
            bgp_large_community.add((4242422024,2,100)); # origin identify: from downstream
            # consider our own prefix as customer and treat as downstream
            accept;
        };
        export none;
    };
}

protocol static dn42_static_v6{
    route DN42_OWNNETv6 reject;
    route fd18:3e15:61d0::3/128 reject{
        bgp_large_community.add((4242422024,2,0)); # origin identify: private network
    };

    ipv6 {
        import filter{
            bgp_large_community.add((4242422024,1,1)); # control: allow route to be advertised on DN42 infrastructures
            bgp_large_community.add((4242422024,2,100)); # origin identify: from downstream
            # consider our own prefix as customer and treat as downstream
            accept;
        };
        export none;
    };
}
