description: '@zxxwdd'
asn: 4242420337
wireguard:
  public_key: WdvyDf+lEAar5MbcFYUVhvQXzWg2ZXi9Jt1860Q41y4=
  listen_port: 20337
  fwmark: '4242'
  endpoint: hkg02.dn42.wwrr.ru:22024
lla: fe80::337
bgp:
  extended_next_hop: true
