description: '@cmcc1686 https://dn42.guet.eu.org/zh-cn/contact/'
asn: 4242421686
wireguard:
  public_key: D4MBIR+HsCPeEGuPg1YziRe1RgaG7jaiTw4wmV8XZUY=
  listen_port: 21686
  fwmark: '4242'
  endpoint: hk-1.dn42.guet.eu.org:22024
lla: fe80::1686
bgp:
  extended_next_hop: true
