description: '@MadobiNanami https://blog.nanami.tech/'
asn: 4242420055
wireguard:
  public_key: ifY8fh4xZuIVF10FJ5PYnJBkN/NuMpLscK5serYUfBw=
  listen_port: 20055
  fwmark: '4242'
  endpoint: 154.83.86.10:22024
lla: fe80::55
bgp:
  extended_next_hop: true
