iana:
  enabled: true
  upstreams:
  - protocol: iana_upstream_44324
    description: MoeDove
    neighbor:
      address: fc00:32e0::1
      asn: 44324
  downstreams: 
  - protocol: iana_downstream_219489
    local: fc00:32e0::3200:1
    neighbor:
      address: fc00:32e0::8800:1
      asn: 219489
  peers:
  - protocol: iana_ix_zxix_rs1
    local: 2406:840:1f:1000::20:5369:1
    neighbor:
      address: 2406:840:1f:1000::1
      asn: 140961
  - protocol: iana_ix_zxix_rs2
    local: 2406:840:1f:1000::20:5369:1
    neighbor:
      address: 2406:840:1f:1000::2
      asn: 140961
  - protocol: iana_ix_akix
    local: 2602:f92a:1315:2::34
    neighbor:
      address: 2602:f92a:1315:2::1
      asn: 203168
  ibgp:
    enabled: false
    sessions: []
  static:
    advertise_routes:
    - "2a14:7583:f220::/43"
    - IANA_AnycastNETv6
    extra_routes:
    - name: iana_local_route_advertise
      prefixes:
      - prefix: IANA_OWNNETv6
        communities:
        - NO_EXPORT
  own_ipv6: 2a14:7583:f224::7d89
  own_net_v6: 2a14:7583:f220::/43
  own_netset_v6: '[ 2a14:7581:0ffb::/48+, 2a14:7583:f200::/40+, 2a14:67c3:fff0::/44+,
    2a14:67c3:c0::/44+ ]'
  router_id: 23.149.120.51
  allow_netset_v6: '[]'
