bird:
  log_syslog_all: false
  device_scan_time: 10
  device_semicolon: false
modules:
  iana:
    enabled: false
    includes: []
  dn42:
    enabled: true
    includes:
    - filter.conf
    - flapalerted.conf
    - ix.conf
    inactive_files:
    - rpki.conf
  intra:
    enabled: true
    includes:
    - filter.conf
    - ibgp.conf
    - static.conf
intra:
  static:
    v4_routes:
    - prefix: 172.20.234.226/32
    v6_routes:
    - prefix: fd18:3e15:61d0::2/128
