node:
  name: fra02-de
  tier: 2
  region: 2
  node_id: 2
  node_token: "d131"
  peering:
    enabled: false
deploy:
  service_manager: openrc
  bird:
    enabled: true
  wireguard:
    enabled: true
