define INTRA_ROUTER_ID      = 100.64.1.82;
define INTRA_PREFIX_V4      = [ 100.64.0.0/16+ ];
define INTRA_PREFIX_V6      = [ fd18:3e15:61d0::/48+ ];

function is_intra_net4() {
    return net ~ INTRA_PREFIX_V4;
}

function is_intra_net6(){
    return net ~ INTRA_PREFIX_V6;
}

function is_intra_dn42_net4(){
    return net ~ [ 172.20.0.0/14+ ];
}

function is_intra_dn42_net6(){
    return net ~ [ fd00::/8+ ];
}
