function intra_should_export(){
    if !(bgp_large_community ~ [(205369,2000,0)]) then 
        return false;
    
    if bgp_large_community ~ [(205369,2000,666)] then
        return false;
    
    return true;
}