protocol kernel intra_kernel_v6{
    kernel table 254;
    scan time 20;

    ipv6 {
        table intra_table_v6;
        import none;
        export all;
    };
};

protocol kernel intra_kernel_v4{
    kernel table 254;
    scan time 20;

    ipv4 {
        table intra_table_v4;
        import none;
        export all;
    };
}
