protocol static intra_static_v4{
    route 172.20.234.229/32 reject{
        bgp_large_community.add((4242422024,1,1)); # control: allow route to be advertised on DN42 infrastructures
        bgp_large_community.add((4242422024,2,0)); # origin identify: private network
        bgp_large_community.add((4242422024,2,100)); # origin identify: from downstream
        bgp_large_community.add((4242422024,65535,65281)); # origin identify: from downstream
    };

    ipv4 {
        import all;
        export none;
    };
}

protocol static intra_static_v6{
    route fd18:3e15:61d0::5/128 reject{
        bgp_large_community.add((4242422024,1,1)); # control: allow route to be advertised on DN42 infrastructures
        bgp_large_community.add((4242422024,2,0)); # origin identify: private network
        bgp_large_community.add((4242422024,2,100)); # origin identify: from downstream
        bgp_large_community.add((4242422024,65535,65281)); # origin identify: from downstream
    };

    ipv6 {
        import all;
        export none;
    };
}
