bird:
  log_syslog_all: false
  device_scan_time: 10
  device_semicolon: false
modules:
  iana:
    enabled: false
  dn42:
    enabled: true
  intra:
    enabled: true
intra:
  static:
    v4_routes:
    - prefix: 172.20.234.229/32
    v6_routes:
    - prefix: fd18:3e15:61d0::5/128
