dn42:
  own_ip: 172.20.234.229
  own_ipv6: fd18:3e15:61d0::5
  region: 44
  country: 1840
  flapalerted:
    local: 172.20.234.229
    neighbor:
      address: 172.20.234.232
      port: 1790
    rpki_remote:
      address: 172.20.234.232
      port: 8083
  peers:
  - description: '@lyc8503 http://blog.lyc8503.net/'
    asn: 4242420167
    wireguard:
      public_key: IRpAYNTZg1YKumLqOstDOLh6iJKAwQEKC5YDFPb2Bm4=
      listen_port: 20167
      endpoint: sfo1.dn42.42420167.xyz:22024
    lla: fe80::167
    bgp:
      extended_next_hop: true
  - description: https://dn42.routedbits.io/
    asn: 4242420207
    wireguard:
      public_key: s4uGYMeLV30vO/Z3+c1qrg/YA1eIMRVFYUsZEGD1hH8=
      listen_port: 20207
      endpoint: router.lax1.routedbits.com:52024
    lla: fe80::207
    bgp:
      extended_next_hop: true
  - description: 22024 creamlike1024@outlook.com https://blog.moe233.net/dn42/
    asn: 4242420253
    wireguard:
      public_key: C3SneO68SmagisYQ3wi5tYI2R9g5xedKkB56Y7rtPUo=
      listen_port: 20253
      endpoint: lv.dn42.moe233.net:22024
    lla: fe80::253
    bgp:
      extended_next_hop: true
  - description: '@Nuro_Atamashino'
    asn: 4242420298
    wireguard:
      public_key: qp/KHe+/6jf3/Cvbkw5/0gtJih+HzhpxW0UnLXMEHiw=
      listen_port: 20298
      endpoint: node3.ox5.cc:22024
    lla: fe80::298
    bgp:
      extended_next_hop: true
  - description: '@zxxwdd'
    asn: 4242420337
    wireguard:
      public_key: QK813SDMiaIhfBw9VOkpTCgQSLdUNFDmSphymv5c7To=
      listen_port: 20337
      mtu: 1320
      endpoint: lax01.dn42.wwrr.ru:22024
    lla: fe80::337
    bgp:
      extended_next_hop: true
  - description: '@X01512'
    asn: 4242420358
    wireguard:
      public_key: 7HzHyeA2M7yo/zVmc+e0zG+I7j2SnIx+7ZpXOca93mg=
      listen_port: 20358
      endpoint: 45.32.129.207:22024
    lla: fe80::358
    bgp:
      extended_next_hop: true
  - description: '@opkgbot'
    asn: 4242420398
    wireguard:
      public_key: oAPy0U2qVuSR8PyPLmVLEgWLBKrOq4kcLNLAOVZL10M=
      listen_port: 20398
      endpoint: lax.dn42.boletus.icu:22024
    lla: fe80::398
    bgp:
      extended_next_hop: true
  - description: https://anemone.moe/posts/dn42-quickstart/ fermata@h2o.moe
    asn: 4242420721
    wireguard:
      public_key: HBn/8dyDkC8z4kY5tGZsG3d7iyyc8SWwl5c93po580w=
      listen_port: 20721
      endpoint: 24.199.110.90:22024
    lla: fe80::721:1
    bgp:
      extended_next_hop: true
  - description: dn42admin@maiyun.me https://maiyun.me/contact-me.html
    asn: 4242420893
    wireguard:
      public_key: 6BFCe8vi6R9magcs/BqZbSqblNNqR/jcrNt1E7/NDD8=
      listen_port: 20893
      endpoint: uc01.dn42.maiyun.me:24224
    lla: fe80::893
    bgp:
      extended_next_hop: true
  - description: '@Iridoideae'
    asn: 4242421023
    wireguard:
      public_key: yHtmGTi6r9AtrSeTZyl2yce6nHdSVcc017VMI1s9HH8=
      listen_port: 21023
      endpoint: lax-02.node.svc.moe:22024
    lla: fe80::1023:2
    bgp:
      extended_next_hop: true
  - description: '@antenna000 https://blog.yuyuko.com/post/7'
    asn: 4242421117
    wireguard:
      public_key: PW/+rv0B8e4tUJ9j1TWscx1sl36WwhPh9adEqoM7Jic=
      listen_port: 21117
      endpoint: us01.dn42.yuyuko.com:22024
    lla: fe80::1117
    bgp:
      extended_next_hop: true
  - description: '@temu_root https://dn42.fly.dev/'
    asn: 4242421123
    wireguard:
      public_key: Z6OKJSR1sxMBgUd1uXEe/UxoBsOvRgbTnexy7z/ryUI=
      listen_port: 21123
      mtu: 1340
    lla: fe80::1123
    bgp:
      extended_next_hop: true
  - description: factor2431@outlook.com @factor2431
    asn: 4242421534
    wireguard:
      public_key: G2pN3V0dtE/fGltPoOPwEkvZ7wC7TLmpr9gR3x/QUTk=
      listen_port: 21534
      endpoint: 152.53.208.136:22024
    lla: fe80::1534
    bgp:
      extended_next_hop: true
  - description: '@messageleaf https://exploro.one/dn42'
    asn: 4242421771
    wireguard:
      public_key: XC+KJ25WHrn6WxPYkiQOj1FPcaKgMRD4cCyxahqr1Ws=
      listen_port: 21771
      endpoint: 148.135.56.215:32629
    lla: fe80::1771
    bgp:
      extended_next_hop: true
  - description: https://dn42.kskb.eu.org/
    asn: 4242421817
    wireguard:
      public_key: dZzVdXbQPnWPpHk8QfW/p+MfGzAkMBuWpxEIXzQCggY=
      listen_port: 21817
      endpoint: us.kskb.eu.org:22024
    lla: fe80::1817
    bgp:
      extended_next_hop: true
  - description: '@daylilies https://daylily.network/dn42'
    asn: 4242421919
    wireguard:
      public_key: yOt9PIXDa4pzAE+XMzDv7J+CYO2qf53fnF9MvLy4iQ8=
      listen_port: 21919
      endpoint: 149.28.212.242:42024
    lla: fe80::1919
    bgp:
      extended_next_hop: true
  - description: https://iedon.net
    asn: 4242422189
    wireguard:
      public_key: DIw4TKAQelurK10Sh1qE6IiDKTqL1yciI5ItwBgcHFA=
      listen_port: 22189
      endpoint: us-lax.dn42.iedon.net:57115
    lla: fe80::2189:ef
    bgp:
      extended_next_hop: true
  - description: '@moohric https://www.mhr.hk/posts/dn42-peering/'
    asn: 4242422279
    wireguard:
      public_key: WCVsWHNq+VeafZ7agkfkafZIoC/8oHF46D07PkOVljA=
      listen_port: 22279
      endpoint: us-sjc1.bb.mhr.hk:22024
    lla: fe80::2279
    bgp:
      extended_next_hop: true
  - description: '@SessX6cf https://dn42.xhustudio.eu.org/peering.html'
    asn: 4242422466
    wireguard:
      public_key: tA6SZZYpCdr4zkkk2pCpuDDiyxcHIsksOhwWnzLIVw8=
      listen_port: 22466
      endpoint: 23.95.205.128:22024
    lla: fe80::2466
    bgp:
      extended_next_hop: true
  - description: '@unstartdev https://unstartdev.eu.org/dn42'
    asn: 4242422467
    wireguard:
      public_key: Nn73gI6XYCHxKWybWPwFgNQM8/s5R3UzN6VqutUC/3s=
      listen_port: 22467
      endpoint: 77.111.110.27:22024
    lla: fe80::2467
    bgp:
      extended_next_hop: true
  - description: 23154 https://usw42.whojk.com/autopeer/action_page.php
    asn: 4242422717
    wireguard:
      public_key: L4+efr10ZM0J80nDeO5mHw25nq9LC5UBrYtP8T1I9n4=
      listen_port: 22717
      endpoint: usw.vm.whojk.com:23154
    lla: fe80::2717
    bgp:
      extended_next_hop: true
  - description: https://peer.dn42.6700.cc
    asn: 4242423088
    wireguard:
      public_key: QSAeFPotqFpF6fFe3CMrMjrpS5AL54AxWY2w1+Ot2Bo=
      listen_port: 23088
      endpoint: lax1-us.dn42.6700.cc:22024
    lla: fe80::3088:193
    bgp:
      extended_next_hop: true
  - description: '@WOW55999 https://dn42.gtio.de/'
    asn: 4242423128
    wireguard:
      public_key: YwnQqLlObD7TrpGKz4qhHh5C6hatuxIU3zcdjXpYP00=
      listen_port: 23128
      endpoint: dn42.la.us.gtio.de:52024
    lla: fe80::1:3128
    bgp:
      extended_next_hop: true
  - description: '@Auride'
    asn: 4242423310
    wireguard:
      public_key: qEffOA35Oe2IFUFXv7KTGGZ5SV3XmrM+IxTdzHEDmCg=
      listen_port: 23310
      endpoint: v4.lax01.edge.r1.tmpfs.dev:22024
    lla: fe80::2024:3310
    bgp:
      extended_next_hop: true
  - description: x@badaimweeb.me
    asn: 4242423797
    wireguard:
      public_key: 4RtBDlHlTLec0ThvkGKjwiyuDk0YspugIMHeUdaNZmE=
      listen_port: 23797
      endpoint: 155.94.164.158:50097
      preshared_key_ref: lax01-us/dn42_4242423797
    lla: fe80::3797
    bgp:
      extended_next_hop: true
  - description: https://dn42.g-load.eu
    asn: 4242423914
    wireguard:
      public_key: sLbzTRr2gfLFb24NPzDOpy8j09Y6zI+a7NkeVMdVSR8=
      listen_port: 23914
      endpoint: us3.g-load.eu:22024
    lla: fe80::ade0
    bgp:
      extended_next_hop: true
  - description: '@charliemoomoo https://hackmd.io/@cow/dn42-peering#Nodes'
    asn: 4242423999
    wireguard:
      public_key: jhOukGNAKHI8Ivn8uI1TS25n5ho/rVlKFfenGmwCVlg=
      listen_port: 23999
      endpoint: lax.node.cowgl.tech:22024
    lla: fe80::2:3999
    bgp:
      extended_next_hop: true
  ix:
    sessions: []
