intra_peers:
- node: fra01-de
  interface: intra_fra01
  wireguard:
    public_key: 4zEFOrqHdIDPcjvu6NwbE1AAYBH1bA+SAowysX5fRT4=
    listen_port: 10228
    address_mode: intra_local
  bgp:
    file: fra01.conf
    protocol: intra_ibgp_fra01
- node: hkg02-hk
  interface: intra_hkg02
  wireguard:
    public_key: bg+KnzVupBrOQntHFFVzvBx+3sqYVoyJRantT6m5fm8=
    listen_port: 10225
    address_mode: intra_local
  bgp:
    file: hkg02.conf
    protocol: intra_ibgp_hkg02
- node: tyo01-jp
  interface: intra_tyo01
  wireguard:
    public_key: Sh62ZCxnEcXyLq49mLP1jF4C2vWKhKMxjtZHxVUAQg4=
    listen_port: 10227
    address_mode: intra_local
  bgp:
    file: tyo01.conf
    protocol: intra_ibgp_tyo01
