node:
  name: lax01-us
  tier: 1
  region: 4
  node_id: 1
  node_token: "de75"
  peering:
    enabled: true
deploy:
  service_manager: systemd
  bird:
    enabled: true
  wireguard:
    enabled: true
