wireguard:
  default_private_key_ref: lax01-us/default
  interfaces:
  - name: dn42_4242420150
    address:
    - fe80::2024/64
    listen_port: 20150
    table: 'off'
    peer:
      public_key: 1o0XfQvBM1gqknqzfuOnVmf2RjRTHuyMZYNipSSb2TQ=
      allowed_ips:
      - 10.0.0.0/8
      - 172.20.0.0/14
      - 172.31.0.0/16
      - fd00::/8
      - fe00::/8
      endpoint: iad.darkpoint.xyz:22024
    post_up:
    - sysctl -w net.ipv6.conf.%i.autoconf=0
