protocol bgp dn42_flapalerted {
    router id DN42_OWNIP;
    local 172.20.234.229 as DN42_OWNAS; # This address cannot be ::1, it must be another address assigned to the host
    neighbor 172.20.234.227 as DN42_OWNAS port 1790;

    ipv4 {
        table master4;
        add paths on;
        export where bgp_large_community ~ [(4242422024,1,1)]; # control: allow route to be advertised on DN42 infrastructures
        import none;
        extended next hop on;
    };

    ipv6 {
        table master6;
        add paths on;
        export where bgp_large_community ~ [(4242422024,1,1)]; # control: allow route to be advertised on DN42 infrastructures
        import none;
    };
}

roa4 table dn42_roa_flap_v4;
roa6 table dn42_roa_flap_v6;

protocol rpki dn42_rpki_flapalerted {
    roa4 { table dn42_roa_flap_v4; };
    roa6 { table dn42_roa_flap_v6; };
    remote 172.20.234.227 port 8083; # 修改成 StayRTR 监听的端口
    max version 1;
    retry keep 10;
};
