iana:
  enabled: true
  upstreams6: []
  downstreams: []
  peers: []
  ibgp:
    enabled: false
    sessions: []
  static:
    advertise_routes:
    - prefix: "2a14:7583:f220::/43"
      communities:
        - [205369, 670, 6939]
    extra_routes:
    - protocol: iana_static
      prefixes: []
  router_id: 103.213.4.103
