# Node: IEPL @ SparkVM
# https://sparkvm.net/
#
# Port mapping: 13201~13215
# szx-cn.ecs.iyoroy-infra.top:13200 -> 22
# :13201 -> pvg01

wireguard:
  default_private_key_ref: hkg04-hk/default
  interfaces:
