
protocol static inet_static_advertise{
    route INET_OWNNETv6 reject;
    route INET_AnycastNETv6 reject;

    ipv6 {
        import filter{
            bgp_large_community.add((205369,1000,205369));
            bgp_large_community.add((205369,2000,1));
            accept;
        };
        export none;
    };
}

protocol static inet_static{
    route fc00:230::/64 via "eth0";
    
    ipv6 {
        import filter{
            bgp_large_community.add((205369,2000,666));
            accept;
        };
        export none;
    };
}