bird_nodes:
  vars:
    ansible_user: root
    ansible_ssh_private_key_file: ~/keys/default/id_ed25519
  hosts:
    fra01-de:
      ansible_host: ipv4.fra01-de.ecs.iyoroy-infra.top
    fra02-de:
      ansible_host: ipv6.fra02-de.ecs.iyoroy-infra.top
    hkg01-hk:
      ansible_host: ipv4.hkg01-cn.ecs.iyoroy-infra.top
    hkg02-hk:
      ansible_host: ipv4.hkg02-cn.ecs.iyoroy-infra.top
    hkg03-hk:
      ansible_host: ipv4.hkg03-cn.ecs.iyoroy-infra.top
    lax01-us:
      ansible_host: ipv4.lax-us.ecs.iyoroy-infra.top
    tyo01-jp:
      ansible_host: ipv4.tyo-jp.ecs.iyoroy-infra.top
    tyo02-jp:
      ansible_host: ipv4.tyo02-jp.ecs.iyoroy-infra.top
    tyo03-jp:
      ansible_host: 114.111.176.35
      ansible_port: 6400
      ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q -i ~/keys/default/id_ed25519 root@pvg-cn.ecs.iyoroy-infra.top"'
    pvg01-cn:
      ansible_host: ipv4.pvg-cn.ecs.iyoroy-infra.top
    hkg04-hk:
      ansible_host: ipv4.szx-cn.ecs.iyoroy-infra.top
      ansible_port: 13200
      ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q -i ~/keys/default/id_ed25519 root@pvg-cn.ecs.iyoroy-infra.top"'
    cdg01-fr:
      ansible_host: ipv4.cdg01-fr.ecs.iyoroy-infra.top
      ansible_port: 50224