bird_nodes:
  vars:
    ansible_connection: local
    ansible_python_interpreter: /usr/bin/python3
  hosts:
    fra01-de:
    fra02-de:
    hkg01-hk:
    hkg02-hk:
    hkg03-hk:
    lax01-us:
    tyo01-jp:
    tyo02-jp:
    tyo03-jp:
    pvg01-cn:
    hkg04-hk:
    cdg01-fr:
