description: '@Auride'
asn: 4242423310
wireguard:
  public_key: qEffOA35Oe2IFUFXv7KTGGZ5SV3XmrM+IxTdzHEDmCg=
  listen_port: 23310
  endpoint: v4.lax01.edge.r1.tmpfs.dev:22024
lla: fe80::2024:3310
bgp:
  extended_next_hop: true
